/**
 * SEO structured-data (JSON-LD) builders.
 *
 * Pages pass the returned objects to `<BaseLayout jsonLd={...}>`, which renders
 * each as a `<script type="application/ld+json">`. URLs are absolute against the
 * canonical site domain (kept in sync with `astro.config.mjs` `site`).
 */

import { type Locale, localizePath } from '@/i18n/locale';

export const SITE = {
  name: 'profedeeconomia',
  url: 'https://www.profedeeconomia.es',
  locale: 'es-ES',
  description:
    'Material editorial para profesores de instituto de economía, empresa y finanzas: libros, diapositivas, actividades, tests y recursos por asignatura.',
} as const;

/** Verified public profiles for the brand entity (schema.org `sameAs`).
 * Only list profiles that actually exist — a broken link is worse than none. */
export const SAME_AS = [
  'https://instagram.com/profedeeconomia',
  'https://oposicioneseconomia.es',
] as const;

/** Topics the organization is an authority on (schema.org `knowsAbout`). */
const KNOWS_ABOUT = [
  'Economía',
  'Empresa',
  'Finanzas',
  'Emprendimiento',
  'Currículo LOMLOE',
  'Bachillerato',
  'ESO',
  'Formación Profesional',
] as const;

/**
 * Google renders roughly 600px of title text; 60 characters is the usual safe
 * proxy for that in a Latin-script title.
 */
export const MAX_TITLE_CHARS = 60;

const BRAND_SUFFIX = ` — ${SITE.name}`;

/**
 * Compose the `<title>`: append the brand only when it still fits inside the
 * display budget. Past that point Google truncates from the right, so the
 * suffix is invisible anyway and only displaces words that would have shown —
 * and Google appends the site name itself from `og:site_name`.
 * See docs/seo-estrategia-2026.md §5.7.
 */
export function pageTitle(title: string, brandSuffix = true): string {
  if (!brandSuffix || title.endsWith(SITE.name)) return title;
  return title.length + BRAND_SUFFIX.length <= MAX_TITLE_CHARS ? `${title}${BRAND_SUFFIX}` : title;
}

/** Resolve a site-relative path to an absolute URL on the canonical domain. */
export const absUrl = (path: string): string => new URL(path, SITE.url).toString();

/** schema.org BCP-47 language tag for a site locale. */
const inLang = (locale: Locale = 'es'): string => (locale === 'ca' ? 'ca-ES' : 'es-ES');

/**
 * Absolute URL for a page in the given locale, so JSON-LD `url`/`mainEntityOfPage`
 * match the page's own canonical (`/ca/...` for Valencian pages).
 */
const absUrlL = (path: string, locale: Locale = 'es'): string => absUrl(localizePath(path, locale));

// Raster brand logo (512×512 PNG, generated by scripts/build-logo.mjs) — Google's
// logo rich result wants a raster image, not the favicon SVG.
const LOGO = { '@type': 'ImageObject', url: absUrl('/logo-512.png'), width: 512, height: 512 };

const orgRef = () => ({
  '@type': 'Organization',
  name: SITE.name,
  url: SITE.url,
  logo: LOGO,
  sameAs: [...SAME_AS],
});

/** schema.org EducationalOrganization — emit once, on the home page. */
export function organizationLd(locale: Locale = 'es') {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    name: SITE.name,
    url: SITE.url,
    logo: LOGO,
    description: SITE.description,
    inLanguage: inLang(locale),
    knowsAbout: [...KNOWS_ABOUT],
    sameAs: [...SAME_AS],
  };
}

/** schema.org WebSite — emit once, on the home page. */
export function websiteLd(locale: Locale = 'es') {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: SITE.name,
    url: SITE.url,
    inLanguage: inLang(locale),
    publisher: orgRef(),
  };
}

/** schema.org BreadcrumbList from an ordered list of `{ name, path }`. */
export function breadcrumbLd(items: { name: string; path: string }[], locale: Locale = 'es') {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((it, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: it.name,
      item: absUrlL(it.path, locale),
    })),
  };
}

/**
 * Serialize a JSON-LD object to a string safe for inline `<script>` injection.
 * JSON.stringify does not escape `<`, so a title containing `</script>` could
 * break out of the script tag. We replace `<` with the Unicode escape `<`.
 */
export function jsonLdToString(obj: object): string {
  return JSON.stringify(obj).replace(/</g, '\\u003c');
}

/**
 * schema.org Article + LearningResource for a long-form educational page
 * (e.g. a book unit). The dual type tells AI/search what the page teaches and
 * to whom — exactly the metadata that gets a page cited as a learning source.
 */
export function articleLd(opts: {
  title: string;
  description: string;
  path: string;
  datePublished?: string;
  /** Last meaningful content edit; falls back to datePublished when absent. */
  dateModified?: string;
  section?: string;
  /** Absolute or site-relative image URL (e.g. the per-asignatura OG image). */
  image?: string;
  /** Educational stage, e.g. "2.º Bachillerato". */
  educationalLevel?: string;
  /** Key concepts the unit teaches (schema.org `teaches`). */
  teaches?: string[];
  /** Content language of the rendered page (drives inLanguage + canonical URL). */
  locale?: Locale;
}) {
  const ld: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': ['Article', 'LearningResource'],
    headline: opts.title,
    description: opts.description,
    inLanguage: inLang(opts.locale),
    mainEntityOfPage: absUrlL(opts.path, opts.locale),
    isAccessibleForFree: true,
    learningResourceType: 'Unidad didáctica',
    author: orgRef(),
    publisher: orgRef(),
  };
  if (opts.image) ld.image = absUrl(opts.image);
  if (opts.datePublished) ld.datePublished = opts.datePublished;
  if (opts.dateModified ?? opts.datePublished)
    ld.dateModified = opts.dateModified ?? opts.datePublished;
  if (opts.section) ld.articleSection = opts.section;
  if (opts.educationalLevel) ld.educationalLevel = opts.educationalLevel;
  if (opts.teaches && opts.teaches.length) ld.teaches = opts.teaches;
  return ld;
}

/**
 * schema.org Course for an asignatura hub. Each of the 9 subjects is a course;
 * `educationalAlignment` to the LOMLOE Real Decreto is a differentiator almost
 * no Spanish education site emits.
 */
export function courseLd(opts: {
  name: string;
  description: string;
  path: string;
  educationalLevel: string;
  /** LOMLOE framework reference, e.g. "Real Decreto 243/2022". */
  marcoNormativo: string;
  /** Target curriculum name, e.g. "Empresa y Diseño de Modelos de Negocio, 2.º Bachillerato". */
  targetName: string;
  teaches?: string[];
  /** Content language of the rendered page (drives inLanguage + canonical URL). */
  locale?: Locale;
}) {
  const ld: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'Course',
    name: opts.name,
    description: opts.description,
    url: absUrlL(opts.path, opts.locale),
    inLanguage: inLang(opts.locale),
    isAccessibleForFree: true,
    educationalLevel: opts.educationalLevel,
    provider: {
      '@type': 'EducationalOrganization',
      name: SITE.name,
      url: SITE.url,
    },
    educationalAlignment: {
      '@type': 'AlignmentObject',
      alignmentType: 'educationalSubject',
      educationalFramework: `LOMLOE — ${opts.marcoNormativo}`,
      targetName: opts.targetName,
    },
  };
  if (opts.teaches && opts.teaches.length) ld.teaches = opts.teaches;
  return ld;
}

/**
 * schema.org FAQPage from question/answer pairs. The visible Q&A blocks are the
 * real win for AI answer extraction; the JSON-LD is a semantic reinforcement.
 */
export function faqLd(items: { q: string; a: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map((it) => ({
      '@type': 'Question',
      name: it.q,
      acceptedAnswer: { '@type': 'Answer', text: it.a },
    })),
  };
}

/** schema.org ItemList from an ordered list of `{ name, path }` (e.g. a TOC). */
export function itemListLd(opts: { name: string; items: { name: string; path: string }[]; locale?: Locale }) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: opts.name,
    itemListOrder: 'https://schema.org/ItemListOrderAscending',
    numberOfItems: opts.items.length,
    itemListElement: opts.items.map((it, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: it.name,
      url: absUrlL(it.path, opts.locale),
    })),
  };
}

/* ============================================================================
   Quiz — Education Q&A structured data for the per-unit self-assessment tests.
   The one live educational rich result left to us: Google retired FAQ snippets
   for non-institutional sites in 2023 and deprecated practice problems in
   January 2026, but Quiz/Education Q&A still feeds the Q&A carousel in Search,
   Assistant and Lens. It also happens to be something a competitor delivering
   PDFs on Blogger cannot emit at all. See docs/seo-estrategia-2026.md §5.5.

   Google requires the marked-up questions to be the ones a visitor can
   actually answer on the page — here they are, rendered by QuizPlayer from
   the same frontmatter this builder reads.
   ========================================================================= */

/** Question shapes accepted from the `tests` collection frontmatter. */
export type TestQuestion =
  | { tipo: 'opcion-multiple'; enunciado: string; opciones: string[]; correcta: number; explicacion?: string }
  | { tipo: 'verdadero-falso'; enunciado: string; correcta: boolean; explicacion?: string }
  | { tipo: 'numerico'; enunciado: string; respuesta: number; unidad?: string; explicacion?: string }
  | { tipo: 'relacionar'; enunciado: string; explicacion?: string };

/** Strip Markdown emphasis so JSON-LD carries plain text, as the spec expects. */
const plain = (text: string): string =>
  text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/(^|\W)[*_](\S(?:.*?\S)?)[*_](\W|$)/g, '$1$2$3')
    .replace(/`(.+?)`/g, '$1')
    .trim();

const answer = (text: string, explicacion?: string) => ({
  '@type': 'Answer',
  text: plain(text),
  ...(explicacion
    ? { answerExplanation: { '@type': 'Comment', text: plain(explicacion) } }
    : {}),
});

const VF_LABELS = { es: ['Verdadero', 'Falso'], ca: ['Vertader', 'Fals'] } as const;

/**
 * One `Question` node per test question. `relacionar` (matching) questions are
 * skipped: they have no single answer string, so forcing them into the Q&A
 * shape would misrepresent the page.
 */
function questionLd(q: TestQuestion, locale: Locale) {
  const base = { '@type': 'Question', text: plain(q.enunciado) };

  if (q.tipo === 'opcion-multiple') {
    const correct = q.opciones[q.correcta];
    if (correct === undefined) return null;
    return {
      ...base,
      eduQuestionType: 'Multiple choice',
      acceptedAnswer: answer(correct, q.explicacion),
      suggestedAnswer: q.opciones
        .map((opt, i) => ({ opt, i }))
        .filter(({ i }) => i !== q.correcta)
        .map(({ opt, i }) => ({ '@type': 'Answer', text: plain(opt), position: i })),
    };
  }

  if (q.tipo === 'verdadero-falso') {
    const [yes, no] = VF_LABELS[locale === 'ca' ? 'ca' : 'es'];
    return {
      ...base,
      eduQuestionType: 'Multiple choice',
      acceptedAnswer: answer(q.correcta ? yes : no, q.explicacion),
      suggestedAnswer: [{ '@type': 'Answer', text: q.correcta ? no : yes, position: 1 }],
    };
  }

  if (q.tipo === 'numerico') {
    return {
      ...base,
      eduQuestionType: 'Flashcard',
      acceptedAnswer: answer(q.unidad ? `${q.respuesta} ${q.unidad}` : String(q.respuesta), q.explicacion),
    };
  }

  return null;
}

/**
 * schema.org Quiz for a unit self-assessment test. Returns `null` when no
 * question survives mapping, so the page can skip emitting an empty Quiz.
 */
export function quizLd(opts: {
  name: string;
  about: string;
  educationalLevel: string;
  path: string;
  questions: TestQuestion[];
  locale?: Locale;
}) {
  const locale = opts.locale ?? 'es';
  const hasPart = opts.questions.map((q) => questionLd(q, locale)).filter((q) => q !== null);
  if (hasPart.length === 0) return null;
  return {
    '@context': 'https://schema.org',
    '@type': 'Quiz',
    name: opts.name,
    url: absUrlL(opts.path, locale),
    about: { '@type': 'Thing', name: opts.about },
    educationalLevel: opts.educationalLevel,
    inLanguage: inLang(locale),
    publisher: orgRef(),
    hasPart,
  };
}
