/** A banco question: extends QuizPlayer's Pregunta with the thematic block + level. */
export interface PreguntaBanco {
  bloque: string;            // one of BLOQUE_SLUGS
  nivel: 1 | 2 | 3;          // 1 concepto, 2 aplicación, 3 olimpiada
  enunciado: string;
  opciones: string[];
  correcta: number;          // index into opciones
  explicacion?: string;
}

export const BANCO: PreguntaBanco[] = [

  // ─── FPP (Frontera de Posibilidades de Producción) ────────────────────────

  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: 'Los puntos situados por encima de la Frontera de Posibilidades de Producción (FPP) son:',
    opciones: ['Eficientes', 'Alcanzables con tecnología actual', 'Inalcanzables con los recursos actuales', 'Ineficientes'],
    correcta: 2,
    explicacion: 'La FPP delimita la frontera de producción posible con los recursos y tecnología disponibles; todo punto exterior a ella es inalcanzable en el corto plazo.',
  },
  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: '¿Qué representa un punto situado en el interior de la FPP?',
    opciones: ['Producción eficiente', 'Producción inalcanzable', 'Producción ineficiente (recursos ociosos)', 'Producción con pleno empleo'],
    correcta: 2,
    explicacion: 'Un punto interior a la FPP indica que hay recursos sin utilizar o mal asignados, es decir, ineficiencia productiva.',
  },
  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: 'El coste de oportunidad se define como:',
    opciones: ['El precio monetario de un bien', 'El coste de producir una unidad adicional', 'El valor de la mejor alternativa a la que se renuncia al tomar una decisión', 'El coste fijo de producción'],
    correcta: 2,
    explicacion: 'El coste de oportunidad es el valor de la siguiente mejor opción descartada; no es un coste monetario sino un coste de elección.',
  },
  {
    bloque: 'fpp',
    nivel: 2,
    enunciado: 'Un país puede producir como máximo 100 unidades de trigo o 50 de telas si dedica todos sus recursos a un solo bien. Si decide producir 60 de trigo, ¿cuántas telas puede producir como máximo (suponiendo FPP lineal)?',
    opciones: ['20 telas', '30 telas', '40 telas', '50 telas'],
    correcta: 0,
    explicacion: 'Con FPP lineal la tasa de transformación es constante: 100 trigo ↔ 50 telas → 1 trigo = 0,5 telas. Produciendo 60 trigo, quedan 40 unidades de trigo en términos de telas: 40 × 0,5 = 20 telas.',
  },
  {
    bloque: 'fpp',
    nivel: 2,
    enunciado: 'Un avance tecnológico en la producción de bienes industriales, pero no en la producción de alimentos, provocará en la FPP:',
    opciones: ['Un desplazamiento paralelo hacia fuera de toda la curva', 'Un desplazamiento hacia fuera solo en el eje de bienes industriales', 'Un movimiento a lo largo de la curva existente', 'Una contracción de la FPP'],
    correcta: 1,
    explicacion: 'La mejora tecnológica amplía la capacidad productiva únicamente en el sector afectado, por lo que la FPP se expande de forma asimétrica hacia el eje de bienes industriales.',
  },
  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: 'La FPP tiene forma cóncava (curvada hacia el origen) porque:',
    opciones: ['Los recursos son perfectamente adaptables a cualquier uso', 'Los recursos son escasos y tienen usos alternativos con costes de oportunidad crecientes', 'El coste de oportunidad es constante', 'La tecnología es siempre decreciente'],
    correcta: 1,
    explicacion: 'A medida que nos especializamos en un bien, empleamos recursos cada vez menos apropiados para ese uso (los factores no son homogéneos), por lo que el coste de oportunidad aumenta.',
  },
  {
    bloque: 'fpp',
    nivel: 3,
    enunciado: 'En una economía que produce solo robots y naranjas, el coste de oportunidad de la tercera naranja adicional es mayor que el de la segunda. Esto implica que la FPP es:',
    opciones: ['Lineal', 'Convexa respecto al origen', 'Cóncava respecto al origen', 'Horizontal'],
    correcta: 2,
    explicacion: 'El coste de oportunidad creciente es la razón por la que la FPP estándar es cóncava respecto al origen (arqueada hacia fuera): cada unidad adicional de un bien exige sacrificar cantidades mayores del otro.',
  },
  {
    bloque: 'fpp',
    nivel: 2,
    enunciado: 'Un país está produciendo en un punto sobre su FPP. Si mejora su tasa de ahorro e inversión, ¿qué ocurrirá a largo plazo?',
    opciones: ['El punto de producción se moverá al interior de la FPP', 'La FPP se desplazará hacia dentro', 'La FPP se desplazará hacia fuera (crecimiento económico)', 'No ocurrirá ningún cambio en la FPP'],
    correcta: 2,
    explicacion: 'Mayor inversión acumula capital físico y mejora la productividad futura, desplazando la FPP hacia fuera en el largo plazo, lo que representa crecimiento económico.',
  },
  {
    bloque: 'fpp',
    nivel: 3,
    enunciado: 'Si la FPP de un país se contrae, una causa posible es:',
    opciones: ['Un aumento de la población activa', 'Una pandemia que reduce la fuerza laboral disponible', 'Una mejora tecnológica', 'Un aumento de la inversión en capital'],
    correcta: 1,
    explicacion: 'Una reducción de los factores productivos disponibles (como la fuerza laboral por una pandemia) desplaza la FPP hacia dentro, reduciendo la capacidad máxima de producción.',
  },
  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: 'La eficiencia productiva se alcanza cuando:',
    opciones: ['El país produce en cualquier punto del interior de la FPP', 'El país produce sobre la FPP', 'El país produce el máximo posible de ambos bienes a la vez', 'La producción total supera la FPP'],
    correcta: 1,
    explicacion: 'La eficiencia productiva significa que no se puede producir más de un bien sin reducir la producción de otro; esto ocurre exactamente cuando se está sobre la FPP.',
  },
  {
    bloque: 'fpp',
    nivel: 2,
    enunciado: 'La especialización y el comercio internacional permiten a los países consumir:',
    opciones: ['Únicamente sobre su propia FPP', 'Solo en el interior de su FPP', 'Más allá de su propia FPP', 'Menos de lo que producirían sin comercio'],
    correcta: 2,
    explicacion: 'El comercio internacional basado en la ventaja comparativa permite a los países consumir combinaciones que están fuera de su propia FPP, como si dispusieran de más recursos.',
  },
  {
    bloque: 'fpp',
    nivel: 3,
    enunciado: 'Un país A puede producir 200 coches o 400 toneladas de trigo. El país B puede producir 100 coches o 400 toneladas de trigo. ¿Cuál tiene ventaja comparativa en la producción de trigo?',
    opciones: ['El país A', 'El país B', 'Ambos tienen la misma ventaja comparativa en trigo', 'Ninguno tiene ventaja comparativa'],
    correcta: 1,
    explicacion: 'El coste de oportunidad de 1 tonelada de trigo es 0,5 coches en A y 0,25 coches en B. Como B renuncia a menos coches por tonelada de trigo, tiene ventaja comparativa en trigo.',
  },

  // ─── OFERTA-DEMANDA ────────────────────────────────────────────────────────

  {
    bloque: 'oferta-demanda',
    nivel: 1,
    enunciado: 'Los bienes inferiores son aquellos que:',
    opciones: ['Aumentan su demanda cuando sube la renta del consumidor', 'Disminuyen su demanda cuando aumenta la renta del consumidor', 'Tienen demanda perfectamente inelástica', 'Solo se consumen en épocas de crisis'],
    correcta: 1,
    explicacion: 'Un bien inferior tiene elasticidad renta negativa: a mayor renta, los consumidores los sustituyen por bienes de mayor calidad, reduciendo su demanda.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si el precio de los lápices aumenta, ¿qué ocurrirá con la curva de demanda de los bolígrafos (bien sustitutivo)?',
    opciones: ['Se desplazará a la izquierda', 'No se desplazará; habrá movimiento a lo largo de la curva', 'Se desplazará a la derecha', 'El precio de los bolígrafos bajará'],
    correcta: 2,
    explicacion: 'Si los lápices se encarecen, los consumidores los sustituyen por bolígrafos, aumentando la demanda de estos últimos → la curva de demanda de bolígrafos se desplaza a la derecha.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si el precio de los lápices sube y los bolígrafos son sustitutivos, ¿qué ocurrirá en el mercado de bolígrafos?',
    opciones: ['Baja el precio y la cantidad de equilibrio de bolígrafos', 'Sube el precio y la cantidad de equilibrio de bolígrafos', 'Baja el precio pero sube la cantidad de bolígrafos', 'No ocurre nada en el mercado de bolígrafos'],
    correcta: 1,
    explicacion: 'Mayor demanda de bolígrafos (curva D desplazada a la derecha) genera un nuevo equilibrio con mayor precio y mayor cantidad vendida.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 1,
    enunciado: 'Cuando el precio de mercado es inferior al precio de equilibrio:',
    opciones: ['Hay un exceso de oferta', 'Hay un exceso de demanda (escasez)', 'El mercado está en equilibrio', 'Los productores aumentan la oferta inmediatamente'],
    correcta: 1,
    explicacion: 'Por debajo del precio de equilibrio la cantidad demandada supera a la ofrecida, generando escasez (exceso de demanda) que presiona el precio hacia arriba.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si el precio de un bien sube un 30 % y la cantidad demandada cae un 10 %, el ingreso total del vendedor:',
    opciones: ['Baja', 'Sube', 'Se mantiene constante', 'No se puede determinar'],
    correcta: 1,
    explicacion: 'Con elasticidad precio-demanda = 10/30 ≈ 0,33 (inelástica), la subida de precio supera la caída en cantidad, por lo que los ingresos totales (P × Q) aumentan.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'La función de demanda de bocadillos en una cafetería es Qd = 500 − 100P y la oferta Qo = 25P. ¿Cuáles son el precio y la cantidad de equilibrio?',
    opciones: ['P = 4 €; Q = 100', 'P = 5 €; Q = 125', 'P = 4 €; Q = 125', 'P = 5 €; Q = 100'],
    correcta: 0,
    explicacion: 'En equilibrio Qd = Qo → 500 − 100P = 25P → 125P = 500 → P = 4. Sustituyendo: Q = 25 × 4 = 100.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 3,
    enunciado: 'Siguiendo el ejercicio anterior (Qd = 500 − 100P; Qo = 25P), si la demanda pasa a Qd = 700 − 100P, ¿cuál es el nuevo equilibrio?',
    opciones: ['P = 4 €; Q = 100', 'P = 5,6 €; Q = 140', 'P = 5 €; Q = 200', 'P = 6 €; Q = 100'],
    correcta: 1,
    explicacion: '700 − 100P = 25P → 125P = 700 → P = 5,6. Q = 25 × 5,6 = 140. El aumento de demanda eleva precio y cantidad de equilibrio.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si mejora la tecnología en la producción de móviles y empeoran los gustos de los consumidores hacia los móviles, ¿qué ocurre con el precio y la cantidad de equilibrio?',
    opciones: ['Disminuye el precio, pero no sabemos qué pasará con la cantidad', 'Aumenta el precio y la cantidad', 'Disminuye la cantidad, pero no sabemos qué pasará con el precio', 'Ambos aumentan con seguridad'],
    correcta: 0,
    explicacion: 'La mejora tecnológica desplaza la oferta a la derecha (baja el precio) y el empeoramiento de gustos desplaza la demanda a la izquierda (también baja el precio). El precio baja con seguridad; el efecto sobre la cantidad depende de la magnitud relativa de cada desplazamiento.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 1,
    enunciado: 'Una tienda sube el precio del pan (bien inelástico). Sus ingresos totales:',
    opciones: ['Disminuirán, porque venderá menos unidades', 'Aumentarán, porque la caída en cantidad es proporcionalmente menor que la subida de precio', 'Se mantendrán iguales', 'Dependerá de la renta de los consumidores'],
    correcta: 1,
    explicacion: 'Con demanda inelástica (|Ed| < 1), una subida de precio reduce poco la cantidad vendida; el efecto precio domina y el ingreso total (P × Q) sube.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si baja el precio del iPhone 12, su curva de oferta:',
    opciones: ['Se desplaza a la derecha', 'Se desplaza a la izquierda', 'No hay desplazamiento; hay un movimiento a lo largo de la curva de oferta', 'No ocurre ningún cambio'],
    correcta: 2,
    explicacion: 'Un cambio en el precio del propio bien provoca un movimiento a lo largo de la curva de oferta (variación de la cantidad ofrecida), no un desplazamiento de la curva.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 3,
    enunciado: 'En el mercado de bocadillos (Qd = 500 − 100P; Qo = 25P), el Estado fija un precio máximo de 3 €. ¿Qué ocurre?',
    opciones: ['No tiene efecto porque el precio de equilibrio es inferior a 3 €', 'Hay un exceso de oferta de 175 bocadillos', 'Hay un exceso de demanda de 125 bocadillos', 'El mercado alcanza el equilibrio a ese precio'],
    correcta: 2,
    explicacion: 'Con P = 3 €: Qd = 500 − 300 = 200; Qo = 75. Exceso de demanda = 200 − 75 = 125 bocadillos. El precio máximo de 3 € es vinculante porque está por debajo del equilibrio (4 €).',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Suben el precio de las motos y bajan los salarios de los mecánicos. ¿Qué ocurre con el precio y la cantidad de equilibrio de los coches (sustitutivos de las motos)?',
    opciones: ['No sabemos qué ocurrirá con precio ni con cantidad', 'Aumenta la cantidad, pero no sabemos qué pasará con el precio', 'Disminuye el precio y aumenta la cantidad', 'Aumentan tanto precio como cantidad'],
    correcta: 1,
    explicacion: 'El encarecimiento de motos desplaza la demanda de coches a la derecha (sube precio y cantidad). Los menores salarios de mecánicos bajan costes de reparación de coches, pudiendo desplazar la demanda de coches también a la derecha. El aumento de cantidad es seguro, pero el precio depende de efectos adicionales sobre la oferta de coches.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 3,
    enunciado: 'La elasticidad precio de la demanda de un bien es −2. Si el precio sube un 5 %, ¿cuánto cambia la cantidad demandada?',
    opciones: ['Sube un 10 %', 'Baja un 2,5 %', 'Baja un 10 %', 'Sube un 2,5 %'],
    correcta: 2,
    explicacion: 'Ed = %ΔQ / %ΔP → −2 = %ΔQ / 5 → %ΔQ = −10 %. La cantidad demandada cae un 10 %, lo que indica una demanda elástica.',
  },

  // ─── PUNTO MUERTO (Producción, costes y umbral de rentabilidad) ─────────────

  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'El punto muerto o umbral de rentabilidad es el nivel de producción en el que:',
    opciones: ['Se maximiza el beneficio', 'Solo se cubren los costes fijos', 'Los ingresos totales igualan a los costes totales (beneficio = 0)', 'Los costes variables son cero'],
    correcta: 2,
    explicacion: 'En el punto muerto (umbral de rentabilidad), IT = CT, es decir, el beneficio es exactamente cero. Por encima de ese punto la empresa empieza a obtener beneficios.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Una empresa tiene costes fijos de 1.000 € y costes variables de 2 € por balón. Si vende los balones a 3 € cada uno, ¿cuántos balones debe vender para alcanzar el punto muerto?',
    opciones: ['500 balones', '1.000 balones', '333 balones', '2.000 balones'],
    correcta: 1,
    explicacion: 'Umbral = CF / (P − Cv) = 1.000 / (3 − 2) = 1.000 balones. A partir de esa cantidad empieza a haber beneficios.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Una empresa produce 1.000 balones con costes fijos de 1.000 € y costes variables de 2 €/ud. Los vende a 3 €/ud. ¿Cuál es el beneficio?',
    opciones: ['0 €', '500 €', '1.000 €', '2.000 €'],
    correcta: 0,
    explicacion: 'IT = 3 × 1.000 = 3.000 €; CT = 1.000 + 2 × 1.000 = 3.000 €; Beneficio = IT − CT = 0 €. La empresa está exactamente en el punto muerto.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'Si una empresa no produce nada, sus pérdidas serán iguales a:',
    opciones: ['Cero, porque no hay producción', 'Sus costes variables totales', 'Sus costes fijos totales', 'Sus ingresos totales esperados'],
    correcta: 2,
    explicacion: 'Los costes fijos se incurren independientemente de la producción. Si la empresa produce cero unidades, IT = 0 y CT = CF, por lo que pierde exactamente sus costes fijos.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'Una empresa produce 5 pantalones con costes fijos de 1.000 € y costes variables de 100 €/unidad. Sus costes fijos totales son:',
    opciones: ['500 €', '1.500 €', '1.000 €', '2.000 €'],
    correcta: 2,
    explicacion: 'Los costes fijos no varían con la producción: siguen siendo 1.000 € independientemente de cuántos pantalones se fabriquen.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'El coste marginal es:',
    opciones: ['El coste total dividido entre las unidades producidas', 'El coste de producir la última unidad adicional', 'Los costes fijos totales', 'La diferencia entre ingresos y costes variables'],
    correcta: 1,
    explicacion: 'El coste marginal (Cmg) mide el incremento en el coste total al producir una unidad más: Cmg = ΔCT / ΔQ.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Si al producir una unidad más el coste marginal baja:',
    opciones: ['La empresa es menos productiva', 'La empresa está siendo más productiva (rendimientos crecientes)', 'El coste total siempre será menor', 'No podemos deducir nada sobre la productividad'],
    correcta: 1,
    explicacion: 'Un coste marginal decreciente indica que la productividad marginal del factor variable está aumentando, es decir, la empresa obtiene más producto por cada unidad adicional de input.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 3,
    enunciado: 'Una empresa transportista tiene como coste variable principal:',
    opciones: ['El Impuesto sobre Bienes Inmuebles del local', 'El seguro anual de los vehículos', 'El combustible consumido en cada ruta', 'La amortización de los camiones'],
    correcta: 2,
    explicacion: 'El combustible varía directamente con los kilómetros recorridos (producción). IBI, seguros y amortización son costes fijos que no dependen del volumen de servicio prestado.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Si el precio de venta de un bien es inferior a su coste marginal de producir una unidad más:',
    opciones: ['El beneficio aumenta al producir esa unidad', 'El beneficio disminuye al producir esa unidad', 'El beneficio no cambia', 'Los ingresos siempre bajarán'],
    correcta: 1,
    explicacion: 'Si P < Cmg, producir una unidad adicional añade menos ingresos que costes, reduciendo el beneficio. La empresa maximiza beneficio cuando P = Cmg.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 3,
    enunciado: 'Una empresa tiene CF = 2.000 €, Cv = 5 € por unidad y precio de venta P = 9 €. ¿Cuántas unidades debe vender para tener un beneficio de 2.000 €?',
    opciones: ['500 unidades', '1.000 unidades', '750 unidades', '400 unidades'],
    correcta: 1,
    explicacion: 'Beneficio = (P − Cv) × Q − CF → 2.000 = (9 − 5) × Q − 2.000 → 4Q = 4.000 → Q = 1.000 unidades.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'Los costes directos de producción son aquellos que:',
    opciones: ['Son independientes del volumen de producción', 'Se asignan de forma clara e inequívoca a cada producto fabricado', 'Necesitan criterios de reparto para distribuirlos entre productos', 'Coinciden siempre con los costes fijos'],
    correcta: 1,
    explicacion: 'Los costes directos son perfectamente identificables y atribuibles a un producto concreto sin necesidad de criterios de asignación arbitrarios.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Una empresa con rendimientos decrecientes a escala dobla todos sus factores de producción. Su producción:',
    opciones: ['Se dobla exactamente', 'Aumenta más del doble', 'Aumenta menos del doble', 'Se mantiene igual'],
    correcta: 2,
    explicacion: 'Con rendimientos decrecientes a escala, un aumento proporcional de todos los factores genera un incremento de producción proporcionalmente menor.',
  },

  // ─── POLÍTICA ECONÓMICA (Monetaria y fiscal) ──────────────────────────────

  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'Para Keynes, la medida más adecuada durante una crisis económica es:',
    opciones: ['Reducir el gasto público para equilibrar el presupuesto', 'Subir los tipos de interés para frenar la inflación', 'Llevar a cabo una política fiscal expansiva (aumentar gasto o reducir impuestos)', 'Dejar que el mercado se corrija solo a largo plazo'],
    correcta: 2,
    explicacion: 'Keynes defendió que en recesiones el Estado debe estimular la demanda agregada mediante aumentos del gasto público o reducciones de impuestos, no esperar al ajuste automático del mercado.',
  },
  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'Si el Estado aumenta los impuestos y reduce el gasto público, está aplicando una política fiscal:',
    opciones: ['Expansiva', 'Contractiva (restrictiva)', 'Monetaria', 'De oferta'],
    correcta: 1,
    explicacion: 'Una política fiscal contractiva (también llamada restrictiva) retira recursos de la economía mediante más impuestos y/o menos gasto público, buscando enfriar la demanda y reducir la inflación.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'Cuando el Estado lleva una política fiscal contractiva, es probable que:',
    opciones: ['El PIB suba y el desempleo baje', 'El PIB baje y el desempleo suba', 'Los precios suban por la mayor demanda', 'El BCE suba automáticamente los tipos de interés'],
    correcta: 1,
    explicacion: 'Al retirar demanda agregada, la política fiscal contractiva tiende a reducir la producción y el empleo, aunque también modera la inflación.',
  },
  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'Las políticas de oferta buscan principalmente:',
    opciones: ['Aumentar el consumo privado a corto plazo', 'Mejorar la productividad y la capacidad productiva de la economía a largo plazo', 'Subir los salarios de los trabajadores de forma directa', 'Aumentar el déficit público para estimular la economía'],
    correcta: 1,
    explicacion: 'Las políticas de oferta actúan sobre los factores de producción y la eficiencia del mercado (educación, I+D, flexibilidad laboral) con el objetivo de aumentar la producción potencial a largo plazo.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'Uno de los problemas del déficit y la deuda pública crecientes es:',
    opciones: ['Que se genera siempre con políticas fiscales contractivas', 'Que obliga a pagar elevados intereses en el futuro, limitando el gasto público disponible', 'Que reduce directamente la inflación del país', 'Que disminuye la prima de riesgo del país'],
    correcta: 1,
    explicacion: 'Un elevado déficit acumulado genera deuda pública que requiere el pago de intereses crecientes, reduciendo el margen para otras políticas y aumentando la prima de riesgo si se pierde confianza.',
  },
  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'Cuando el BCE sube los tipos de interés, el objetivo principal es:',
    opciones: ['Estimular la inversión empresarial', 'Aumentar el consumo de las familias', 'Reducir la inflación enfriando el crédito y la demanda', 'Financiar el déficit de los países de la zona euro'],
    correcta: 2,
    explicacion: 'Tipos de interés más altos encarecen el crédito, reducen el consumo y la inversión, y así moderan la demanda agregada y la inflación. Es el principal instrumento de política monetaria contractiva del BCE.',
  },
  {
    bloque: 'politica-economica',
    nivel: 3,
    enunciado: 'Un banco recibe un depósito de 10.000 € y el coeficiente de caja es del 10 %. ¿Cuánto dinero puede crear el sistema bancario a través del multiplicador del dinero?',
    opciones: ['10.000 €', '100.000 €', '90.000 €', '11.000 €'],
    correcta: 1,
    explicacion: 'El multiplicador del dinero = 1 / coeficiente de caja = 1 / 0,10 = 10. Dinero total creado = 10.000 × 10 = 100.000 €. La banca de reserva fraccional amplifica los depósitos iniciales.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'En un período de expansión económica intensa, lo más habitual es que:',
    opciones: ['El desempleo suba y los precios bajen', 'El desempleo baje y los precios suban (riesgo inflacionario)', 'Tanto el desempleo como los precios bajen', 'El PIB caiga y la inversión aumente'],
    correcta: 1,
    explicacion: 'Durante una expansión, la demanda supera la oferta: el empleo crece (menor desempleo) y los precios tienden a subir por las presiones inflacionarias.',
  },
  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'La macroeconomía estudia principalmente:',
    opciones: ['Por qué sube el precio de los tomates en un mercado local', 'Los costes de producción de una empresa individual', 'Variables agregadas como el PIB, el desempleo y la inflación de un país', 'Las decisiones de consumo de una familia concreta'],
    correcta: 2,
    explicacion: 'La macroeconomía analiza la economía en su conjunto: producción total (PIB), nivel general de precios, tasa de desempleo y relaciones entre grandes sectores, a diferencia de la microeconomía que analiza agentes individuales.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'En el cálculo del PIB por el método del gasto, ¿cuál de las siguientes partidas se suma al PIB español?',
    opciones: ['Lo que un español produce en Francia', 'Lo que produce un inglés residente en España', 'Lo que una empresa española compra como input a una empresa italiana', 'Las exportaciones netas de España'],
    correcta: 1,
    explicacion: 'El PIB mide la producción realizada dentro del territorio, independientemente de la nacionalidad. Un inglés que trabaja en España genera producción que se incluye en el PIB español.',
  },
  {
    bloque: 'politica-economica',
    nivel: 3,
    enunciado: 'Una empresa obtiene madera del bosque y la vende por 5.000 € a otra empresa que fabrica armarios valorados en 9.000 € y los vende a otra que los transforma en mesas vendidas a 12.000 €. ¿En cuánto sube el PIB por estas transacciones?',
    opciones: ['26.000 €', '12.000 €', '21.000 €', '7.000 €'],
    correcta: 1,
    explicacion: 'El PIB por el método del valor añadido suma solo el valor añadido en cada etapa, evitando la doble contabilización. Valor añadido total = 5.000 + (9.000 − 5.000) + (12.000 − 9.000) = 12.000 €.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'Hay inflación cuando:',
    opciones: ['Sube el precio de un bien concreto', 'Sube el nivel general de precios de forma sostenida en el tiempo', 'Suben los precios solo en un mes puntual', 'Baja el poder adquisitivo de forma puntual'],
    correcta: 1,
    explicacion: 'La inflación requiere que sea un fenómeno generalizado (afecte a la mayoría de bienes y servicios) y sostenido en el tiempo. Una subida puntual o de un solo producto no es inflación.',
  },
  {
    bloque: 'politica-economica',
    nivel: 3,
    enunciado: 'El IPC en 2020 era 109, en 2021 era 105 y en 2022 era 115 (base 2015 = 100). La tasa de inflación interanual entre 2021 y 2022 es aproximadamente:',
    opciones: ['−3,7 %', '+9,5 %', '+5,5 %', '+3,2 %'],
    correcta: 1,
    explicacion: 'Tasa inflación 21-22 = (IPC₂₂ − IPC₂₁) / IPC₂₁ × 100 = (115 − 105) / 105 × 100 ≈ 9,52 %. Un fuerte repunte inflacionario en ese período.',
  },

  // ─── MERCADO DE TRABAJO ───────────────────────────────────────────────────

  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'El desempleo estructural se produce cuando:',
    opciones: ['Hay una recesión económica que reduce la demanda de trabajo', 'Hay desajuste entre las cualificaciones de los trabajadores y los puestos disponibles', 'Los trabajadores se encuentran entre dos empleos temporalmente', 'La demanda de trabajo varía según la época del año'],
    correcta: 1,
    explicacion: 'El desempleo estructural surge cuando la oferta y demanda de trabajo no se ajustan cualitativamente: hay vacantes sin cubrir y desempleados que no tienen las habilidades requeridas.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'Un país tiene 5 millones de desempleados, tasa de paro del 25 % y tasa de actividad del 50 %. ¿Cuál es su población en edad de trabajar?',
    opciones: ['12,5 millones', '20 millones', '40 millones', '10 millones'],
    correcta: 2,
    explicacion: 'Tasa paro = desempleados / activos → 0,25 = 5M / activos → activos = 20M. Tasa actividad = activos / PET → 0,50 = 20M / PET → PET = 40 millones.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'Ismael ha dejado su trabajo para tomarse un año sabático. Ismael pertenece a:',
    opciones: ['La población activa desempleada', 'La población ocupada', 'La población inactiva', 'La población activa en búsqueda de empleo'],
    correcta: 2,
    explicacion: 'Una persona que no trabaja y no busca empleo activamente pertenece a la población inactiva (estudiantes, jubilados, personas que se dedican al hogar, etc.).',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'El desempleo friccional:',
    opciones: ['Es muy preocupante porque indica una crisis estructural', 'Es inevitable y transitorio (personas entre empleos o buscando su primer trabajo)', 'Se produce por desajustes de cualificación', 'Se debe a la estacionalidad de ciertos sectores'],
    correcta: 1,
    explicacion: 'El paro friccional existe siempre en toda economía dinámica: refleja el tiempo que tardan las personas en encontrar un nuevo empleo al cambiar de trabajo o al incorporarse al mercado laboral.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 2,
    enunciado: 'La Encuesta de Población Activa (EPA):',
    opciones: ['Cuenta las personas que han cobrado prestación por desempleo en el último año', 'Suele arrojar datos de parados más bajos que el SEPE y es el instrumento usado para comparaciones internacionales', 'Registra a todos los parados inscritos en las oficinas de empleo', 'La realiza el SEPE trimestralmente'],
    correcta: 1,
    explicacion: 'La EPA (elaborada por el INE) utiliza criterios OIT, lo que incluye toda búsqueda activa de empleo, resultando habitualmente en cifras de paro menores que el registro del SEPE. Es el indicador oficial para comparaciones de Eurostat.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'Las políticas pasivas de empleo buscan:',
    opciones: ['Crear puestos de trabajo directamente', 'Mejorar la formación de los desempleados', 'Proporcionar ayudas económicas a las personas desempleadas (subsidios, prestaciones)', 'Reducir el desempleo friccional mediante bolsas de empleo'],
    correcta: 2,
    explicacion: 'Las políticas pasivas son medidas de protección económica (prestaciones por desempleo, subsidios) que ayudan a los parados mientras buscan trabajo, sin actuar directamente sobre la creación de empleo.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 2,
    enunciado: 'Una persona acaba de ser despedida y busca activamente un nuevo trabajo. Está en situación de:',
    opciones: ['Desempleo estructural', 'Desempleo estacional', 'Desempleo friccional', 'Población inactiva'],
    correcta: 2,
    explicacion: 'El desempleo friccional incluye a personas que han perdido o dejado su empleo y están en proceso de búsqueda de uno nuevo; es un desempleo temporal y de transición.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 2,
    enunciado: 'Una persona que busca activamente trabajo pero no lo encuentra se considera:',
    opciones: ['Inactiva', 'Solo activa', 'Desempleada (activa desempleada)', 'Ocupada a tiempo parcial'],
    correcta: 2,
    explicacion: 'Según la OIT, una persona está desempleada si no tiene trabajo, está disponible para trabajar y busca activamente empleo. Pertenece a la población activa pero en su componente desempleado.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 3,
    enunciado: 'El desempleo cíclico o coyuntural se produce principalmente cuando:',
    opciones: ['La economía experimenta una recesión y la demanda de trabajo cae', 'Los trabajadores cambian de empleo voluntariamente', 'Las habilidades de los trabajadores no coinciden con las demandas del mercado', 'La producción agrícola baja fuera de temporada'],
    correcta: 0,
    explicacion: 'El paro cíclico o keynesiano refleja la caída en la demanda agregada durante las recesiones: las empresas producen menos y despiden trabajadores. Se corrige con políticas expansivas que reactiven la economía.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'Los efectos del desempleo incluyen:',
    opciones: ['Reducción del gasto público del Estado', 'Solo efectos negativos para las empresas', 'Estrés y ansiedad social, familias en situación precaria y mayor gasto estatal en prestaciones', 'Aumento de la productividad por la competencia laboral'],
    correcta: 2,
    explicacion: 'El desempleo tiene costes humanos (deterioro psicológico, pobreza), sociales (aumento de desigualdad) y fiscales (más gasto en prestaciones, menos recaudación fiscal).',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 3,
    enunciado: 'En España se puede empezar a trabajar desde los:',
    opciones: ['15 años sin restricciones', '18 años como mínimo en todo caso', '16 años con autorización del tutor legal; nunca antes', '14 años si hay autorización judicial'],
    correcta: 2,
    explicacion: 'El Estatuto de los Trabajadores fija los 16 años como la edad mínima para trabajar en España, siempre con autorización del representante legal si el menor no está emancipado.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 2,
    enunciado: 'Un convenio colectivo es:',
    opciones: ['Un pacto entre trabajadores para aumentar la producción', 'Un acuerdo entre representantes de trabajadores y empresarios para regular condiciones laborales', 'Un acuerdo entre asociaciones empresariales para fijar salarios', 'Una ley aprobada por el Parlamento sobre condiciones de trabajo'],
    correcta: 1,
    explicacion: 'Los convenios colectivos son acuerdos negociados entre sindicatos (representantes de trabajadores) y patronales (representantes empresariales) que fijan salarios, jornada, vacaciones y otras condiciones laborales.',
  },

  // ─── CONTABILIDAD (Balance, resultados, FM, ratios) ──────────────────────

  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'En el balance de situación de una empresa se debe cumplir que:',
    opciones: ['Activo = Patrimonio neto + Pasivo', 'Activo + Patrimonio neto = Pasivo', 'Patrimonio neto = Activo + Pasivo', 'Activo = Pasivo solamente'],
    correcta: 0,
    explicacion: 'La ecuación fundamental del patrimonio establece que Activo = Patrimonio neto + Pasivo. El activo (bienes y derechos) se financia con recursos propios (PN) y ajenos (Pasivo).',
  },
  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'Cuando el fondo de maniobra es negativo significa que:',
    opciones: ['El activo corriente supera al pasivo corriente', 'Parte del activo no corriente está financiada con pasivo corriente (deudas a corto plazo)', 'La empresa tiene quiebra técnica con seguridad', 'El activo corriente está financiado con recursos a largo plazo'],
    correcta: 1,
    explicacion: 'FM = AC − PC < 0 implica que PC > AC; es decir, deudas a corto plazo superan a los activos líquidos, por lo que parte del inmovilizado se financia con deuda a corto: situación financiera delicada.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'Si el activo corriente de una empresa es igual a su pasivo corriente, el fondo de maniobra es:',
    opciones: ['Positivo', 'Negativo', 'Cero', 'Indeterminado'],
    correcta: 2,
    explicacion: 'Fondo de maniobra = Activo corriente − Pasivo corriente = 0. Los activos líquidos cubren exactamente las deudas a corto plazo; la situación es equilibrada aunque sin margen de seguridad.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'Si el ratio de liquidez (activo corriente / pasivo corriente) de una empresa vale 0,74, el fondo de maniobra será:',
    opciones: ['Positivo', 'Negativo', 'Cero', 'No se puede determinar'],
    correcta: 1,
    explicacion: 'Un ratio de liquidez < 1 indica que el activo corriente es menor que el pasivo corriente, por lo que FM = AC − PC < 0 (fondo de maniobra negativo).',
  },
  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'La amortización es:',
    opciones: ['Las pérdidas anuales de la empresa', 'La pérdida de valor del activo no corriente por uso, tiempo u obsolescencia', 'Una deuda con el banco', 'El beneficio no distribuido entre los socios'],
    correcta: 1,
    explicacion: 'La amortización refleja la depreciación sistemática de los activos fijos (maquinaria, instalaciones, vehículos). No es una salida de dinero sino un gasto contable que reduce el valor del activo.',
  },
  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'Los beneficios no distribuidos por la empresa se contabilizan como:',
    opciones: ['Resultado del ejercicio en el pasivo', 'Reservas en el patrimonio neto', 'Proveedores en el pasivo corriente', 'Inmovilizado intangible en el activo'],
    correcta: 1,
    explicacion: 'Los beneficios retenidos (no distribuidos como dividendos) pasan a reservas, que forman parte del patrimonio neto y refuerzan la autofinanciación de la empresa.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'Una deuda con una entidad financiera a devolver en 18 meses se clasifica como:',
    opciones: ['Pasivo no corriente (largo plazo)', 'Activo no corriente', 'Pasivo corriente (corto plazo)', 'Patrimonio neto'],
    correcta: 0,
    explicacion: 'El pasivo no corriente agrupa las deudas con vencimiento superior a un año (12 meses). 18 meses > 12 meses, por lo que esta deuda se registra como pasivo no corriente.',
  },
  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'El resultado de explotación en la cuenta de pérdidas y ganancias representa:',
    opciones: ['El resultado de operaciones financieras', 'El beneficio o pérdida procedente de la actividad principal de la empresa', 'Los ingresos extraordinarios', 'El impuesto de sociedades pagado'],
    correcta: 1,
    explicacion: 'El resultado de explotación (EBIT) recoge los ingresos y gastos de la actividad ordinaria de la empresa, antes de intereses e impuestos. Es el indicador de la rentabilidad operativa.',
  },
  {
    bloque: 'contabilidad',
    nivel: 3,
    enunciado: 'Cuando el ratio de garantía (activo total / exigible total) es igual a la unidad, significa que la empresa:',
    opciones: ['Tiene beneficios elevados', 'Los fondos propios son mayores que las deudas', 'No tiene patrimonio neto (fondos propios = 0, posible quiebra técnica)', 'Tiene el máximo nivel de solvencia'],
    correcta: 2,
    explicacion: 'Activo total = Pasivo total → PN = Activo − Pasivo = 0. La empresa carece de recursos propios (está completamente endeudada), lo que se conoce como quiebra técnica o situación de desbalance.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'Dos empresas tienen la misma cifra de negocio (ventas). ¿Qué podemos afirmar sobre su rentabilidad?',
    opciones: ['Necesariamente tienen la misma rentabilidad económica', 'Necesariamente tienen la misma rentabilidad financiera', 'No significa que tengan la misma rentabilidad: depende también de sus costes y activos', 'La empresa con menor activo tendrá menor rentabilidad'],
    correcta: 2,
    explicacion: 'La rentabilidad económica (BAIT / Activo total) y financiera (BN / Fondos propios) dependen de márgenes y estructura de capital, no solo de las ventas.',
  },
  {
    bloque: 'contabilidad',
    nivel: 3,
    enunciado: 'Los programas informáticos adquiridos por una empresa se contabilizan en el activo como:',
    opciones: ['Equipos para procesos de información (activo material)', 'Material de oficina (gasto corriente)', 'Aplicaciones informáticas (inmovilizado intangible)', 'Existencias (activo corriente)'],
    correcta: 2,
    explicacion: 'Las licencias de software y aplicaciones informáticas son activos intangibles (no tienen forma física) y se registran dentro del inmovilizado intangible del activo no corriente.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'El fondo de maniobra de una empresa es:',
    opciones: ['El capital desembolsado más las reservas', 'La parte del activo corriente financiada con recursos financieros a largo plazo', 'El beneficio neto del ejercicio', 'El total del pasivo corriente de la empresa'],
    correcta: 1,
    explicacion: 'El fondo de maniobra (FM = AC − PC) representa la parte del activo circulante que está financiada con recursos permanentes (propios o ajenos a largo plazo), actuando como colchón de seguridad financiera.',
  },
  {
    bloque: 'contabilidad',
    nivel: 3,
    enunciado: 'Una empresa tiene: Activo no corriente 80.000 €, Activo corriente 20.000 €, Pasivo no corriente 40.000 €, Pasivo corriente 30.000 €. ¿Cuál es su fondo de maniobra y su patrimonio neto?',
    opciones: ['FM = −10.000 €; PN = 30.000 €', 'FM = 10.000 €; PN = 50.000 €', 'FM = −10.000 €; PN = 50.000 €', 'FM = 10.000 €; PN = 30.000 €'],
    correcta: 0,
    explicacion: 'FM = AC − PC = 20.000 − 30.000 = −10.000 € (situación de tensión financiera). PN = Activo total − Pasivo total = 100.000 − 70.000 = 30.000 €.',
  },
];

export function preguntasDeBloque(bloque: string): PreguntaBanco[] {
  return BANCO.filter((p) => p.bloque === bloque);
}
