/** A banco question: extends QuizPlayer's Pregunta with the thematic block + level. */
export interface PreguntaBanco {
  bloque: string;            // one of BLOQUE_SLUGS
  nivel: 1 | 2 | 3;          // 1 concepto, 2 aplicación, 3 olimpiada
  enunciado: string;
  opciones: string[];
  correcta: number;          // index into opciones
  explicacion?: string;
}

export const BANCO: PreguntaBanco[] = [

  // ─── FPP (Frontera de Posibilidades de Producción) ────────────────────────

  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: 'Los puntos situados por encima de la Frontera de Posibilidades de Producción (FPP) son:',
    opciones: ['Eficientes', 'Alcanzables con tecnología actual', 'Inalcanzables con los recursos actuales', 'Ineficientes'],
    correcta: 2,
    explicacion: 'La FPP delimita la frontera de producción posible con los recursos y tecnología disponibles; todo punto exterior a ella es inalcanzable en el corto plazo.',
  },
  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: '¿Qué representa un punto situado en el interior de la FPP?',
    opciones: ['Producción eficiente', 'Producción inalcanzable', 'Producción ineficiente (recursos ociosos)', 'Producción con pleno empleo'],
    correcta: 2,
    explicacion: 'Un punto interior a la FPP indica que hay recursos sin utilizar o mal asignados, es decir, ineficiencia productiva.',
  },
  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: 'El coste de oportunidad se define como:',
    opciones: ['El precio monetario de un bien', 'El coste de producir una unidad adicional', 'El valor de la mejor alternativa a la que se renuncia al tomar una decisión', 'El coste fijo de producción'],
    correcta: 2,
    explicacion: 'El coste de oportunidad es el valor de la siguiente mejor opción descartada; no es un coste monetario sino un coste de elección.',
  },
  {
    bloque: 'fpp',
    nivel: 2,
    enunciado: 'Un país puede producir como máximo 100 unidades de trigo o 50 de telas si dedica todos sus recursos a un solo bien. Si decide producir 60 de trigo, ¿cuántas telas puede producir como máximo (suponiendo FPP lineal)?',
    opciones: ['20 telas', '30 telas', '40 telas', '50 telas'],
    correcta: 0,
    explicacion: 'Con FPP lineal la tasa de transformación es constante: 100 trigo ↔ 50 telas → 1 trigo = 0,5 telas. Produciendo 60 trigo, quedan 40 unidades de trigo en términos de telas: 40 × 0,5 = 20 telas.',
  },
  {
    bloque: 'fpp',
    nivel: 2,
    enunciado: 'Un avance tecnológico en la producción de bienes industriales, pero no en la producción de alimentos, provocará en la FPP:',
    opciones: ['Un desplazamiento paralelo hacia fuera de toda la curva', 'Un desplazamiento hacia fuera solo en el eje de bienes industriales', 'Un movimiento a lo largo de la curva existente', 'Una contracción de la FPP'],
    correcta: 1,
    explicacion: 'La mejora tecnológica amplía la capacidad productiva únicamente en el sector afectado, por lo que la FPP se expande de forma asimétrica hacia el eje de bienes industriales.',
  },
  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: 'La FPP tiene forma cóncava (curvada hacia el origen) porque:',
    opciones: ['Los recursos son perfectamente adaptables a cualquier uso', 'Los recursos son escasos y tienen usos alternativos con costes de oportunidad crecientes', 'El coste de oportunidad es constante', 'La tecnología es siempre decreciente'],
    correcta: 1,
    explicacion: 'A medida que nos especializamos en un bien, empleamos recursos cada vez menos apropiados para ese uso (los factores no son homogéneos), por lo que el coste de oportunidad aumenta.',
  },
  {
    bloque: 'fpp',
    nivel: 3,
    enunciado: 'En una economía que produce solo robots y naranjas, el coste de oportunidad de la tercera naranja adicional es mayor que el de la segunda. Esto implica que la FPP es:',
    opciones: ['Lineal', 'Convexa respecto al origen', 'Cóncava respecto al origen', 'Horizontal'],
    correcta: 2,
    explicacion: 'El coste de oportunidad creciente es la razón por la que la FPP estándar es cóncava respecto al origen (arqueada hacia fuera): cada unidad adicional de un bien exige sacrificar cantidades mayores del otro.',
  },
  {
    bloque: 'fpp',
    nivel: 2,
    enunciado: 'Un país está produciendo en un punto sobre su FPP. Si mejora su tasa de ahorro e inversión, ¿qué ocurrirá a largo plazo?',
    opciones: ['El punto de producción se moverá al interior de la FPP', 'La FPP se desplazará hacia dentro', 'La FPP se desplazará hacia fuera (crecimiento económico)', 'No ocurrirá ningún cambio en la FPP'],
    correcta: 2,
    explicacion: 'Mayor inversión acumula capital físico y mejora la productividad futura, desplazando la FPP hacia fuera en el largo plazo, lo que representa crecimiento económico.',
  },
  {
    bloque: 'fpp',
    nivel: 3,
    enunciado: 'Si la FPP de un país se contrae, una causa posible es:',
    opciones: ['Un aumento de la población activa', 'Una pandemia que reduce la fuerza laboral disponible', 'Una mejora tecnológica', 'Un aumento de la inversión en capital'],
    correcta: 1,
    explicacion: 'Una reducción de los factores productivos disponibles (como la fuerza laboral por una pandemia) desplaza la FPP hacia dentro, reduciendo la capacidad máxima de producción.',
  },
  {
    bloque: 'fpp',
    nivel: 1,
    enunciado: 'La eficiencia productiva se alcanza cuando:',
    opciones: ['El país produce en cualquier punto del interior de la FPP', 'El país produce sobre la FPP', 'El país produce el máximo posible de ambos bienes a la vez', 'La producción total supera la FPP'],
    correcta: 1,
    explicacion: 'La eficiencia productiva significa que no se puede producir más de un bien sin reducir la producción de otro; esto ocurre exactamente cuando se está sobre la FPP.',
  },
  {
    bloque: 'fpp',
    nivel: 2,
    enunciado: 'La especialización y el comercio internacional permiten a los países consumir:',
    opciones: ['Únicamente sobre su propia FPP', 'Solo en el interior de su FPP', 'Más allá de su propia FPP', 'Menos de lo que producirían sin comercio'],
    correcta: 2,
    explicacion: 'El comercio internacional basado en la ventaja comparativa permite a los países consumir combinaciones que están fuera de su propia FPP, como si dispusieran de más recursos.',
  },
  {
    bloque: 'fpp',
    nivel: 3,
    enunciado: 'Un país A puede producir 200 coches o 400 toneladas de trigo. El país B puede producir 100 coches o 400 toneladas de trigo. ¿Cuál tiene ventaja comparativa en la producción de trigo?',
    opciones: ['El país A', 'El país B', 'Ambos tienen la misma ventaja comparativa en trigo', 'Ninguno tiene ventaja comparativa'],
    correcta: 1,
    explicacion: 'El coste de oportunidad de 1 tonelada de trigo es 0,5 coches en A y 0,25 coches en B. Como B renuncia a menos coches por tonelada de trigo, tiene ventaja comparativa en trigo.',
  },

  // ─── OFERTA-DEMANDA ────────────────────────────────────────────────────────

  {
    bloque: 'oferta-demanda',
    nivel: 1,
    enunciado: 'Los bienes inferiores son aquellos que:',
    opciones: ['Aumentan su demanda cuando sube la renta del consumidor', 'Disminuyen su demanda cuando aumenta la renta del consumidor', 'Tienen demanda perfectamente inelástica', 'Solo se consumen en épocas de crisis'],
    correcta: 1,
    explicacion: 'Un bien inferior tiene elasticidad renta negativa: a mayor renta, los consumidores los sustituyen por bienes de mayor calidad, reduciendo su demanda.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si el precio de los lápices aumenta, ¿qué ocurrirá con la curva de demanda de los bolígrafos (bien sustitutivo)?',
    opciones: ['Se desplazará a la izquierda', 'No se desplazará; habrá movimiento a lo largo de la curva', 'Se desplazará a la derecha', 'El precio de los bolígrafos bajará'],
    correcta: 2,
    explicacion: 'Si los lápices se encarecen, los consumidores los sustituyen por bolígrafos, aumentando la demanda de estos últimos → la curva de demanda de bolígrafos se desplaza a la derecha.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si el precio de los lápices sube y los bolígrafos son sustitutivos, ¿qué ocurrirá en el mercado de bolígrafos?',
    opciones: ['Baja el precio y la cantidad de equilibrio de bolígrafos', 'Sube el precio y la cantidad de equilibrio de bolígrafos', 'Baja el precio pero sube la cantidad de bolígrafos', 'No ocurre nada en el mercado de bolígrafos'],
    correcta: 1,
    explicacion: 'Mayor demanda de bolígrafos (curva D desplazada a la derecha) genera un nuevo equilibrio con mayor precio y mayor cantidad vendida.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 1,
    enunciado: 'Cuando el precio de mercado es inferior al precio de equilibrio:',
    opciones: ['Hay un exceso de oferta', 'Hay un exceso de demanda (escasez)', 'El mercado está en equilibrio', 'Los productores aumentan la oferta inmediatamente'],
    correcta: 1,
    explicacion: 'Por debajo del precio de equilibrio la cantidad demandada supera a la ofrecida, generando escasez (exceso de demanda) que presiona el precio hacia arriba.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si el precio de un bien sube un 30 % y la cantidad demandada cae un 10 %, el ingreso total del vendedor:',
    opciones: ['Baja', 'Sube', 'Se mantiene constante', 'No se puede determinar'],
    correcta: 1,
    explicacion: 'Con elasticidad precio-demanda = 10/30 ≈ 0,33 (inelástica), la subida de precio supera la caída en cantidad, por lo que los ingresos totales (P × Q) aumentan.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'La función de demanda de bocadillos en una cafetería es Qd = 500 − 100P y la oferta Qo = 25P. ¿Cuáles son el precio y la cantidad de equilibrio?',
    opciones: ['P = 4 €; Q = 100', 'P = 5 €; Q = 125', 'P = 4 €; Q = 125', 'P = 5 €; Q = 100'],
    correcta: 0,
    explicacion: 'En equilibrio Qd = Qo → 500 − 100P = 25P → 125P = 500 → P = 4. Sustituyendo: Q = 25 × 4 = 100.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 3,
    enunciado: 'Siguiendo el ejercicio anterior (Qd = 500 − 100P; Qo = 25P), si la demanda pasa a Qd = 700 − 100P, ¿cuál es el nuevo equilibrio?',
    opciones: ['P = 4 €; Q = 100', 'P = 5,6 €; Q = 140', 'P = 5 €; Q = 200', 'P = 6 €; Q = 100'],
    correcta: 1,
    explicacion: '700 − 100P = 25P → 125P = 700 → P = 5,6. Q = 25 × 5,6 = 140. El aumento de demanda eleva precio y cantidad de equilibrio.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si mejora la tecnología en la producción de móviles y empeoran los gustos de los consumidores hacia los móviles, ¿qué ocurre con el precio y la cantidad de equilibrio?',
    opciones: ['Disminuye el precio, pero no sabemos qué pasará con la cantidad', 'Aumenta el precio y la cantidad', 'Disminuye la cantidad, pero no sabemos qué pasará con el precio', 'Ambos aumentan con seguridad'],
    correcta: 0,
    explicacion: 'La mejora tecnológica desplaza la oferta a la derecha (baja el precio) y el empeoramiento de gustos desplaza la demanda a la izquierda (también baja el precio). El precio baja con seguridad; el efecto sobre la cantidad depende de la magnitud relativa de cada desplazamiento.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 1,
    enunciado: 'Una tienda sube el precio del pan (bien inelástico). Sus ingresos totales:',
    opciones: ['Disminuirán, porque venderá menos unidades', 'Aumentarán, porque la caída en cantidad es proporcionalmente menor que la subida de precio', 'Se mantendrán iguales', 'Dependerá de la renta de los consumidores'],
    correcta: 1,
    explicacion: 'Con demanda inelástica (|Ed| < 1), una subida de precio reduce poco la cantidad vendida; el efecto precio domina y el ingreso total (P × Q) sube.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Si baja el precio del iPhone 12, su curva de oferta:',
    opciones: ['Se desplaza a la derecha', 'Se desplaza a la izquierda', 'No hay desplazamiento; hay un movimiento a lo largo de la curva de oferta', 'No ocurre ningún cambio'],
    correcta: 2,
    explicacion: 'Un cambio en el precio del propio bien provoca un movimiento a lo largo de la curva de oferta (variación de la cantidad ofrecida), no un desplazamiento de la curva.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 3,
    enunciado: 'En el mercado de bocadillos (Qd = 500 − 100P; Qo = 25P), el Estado fija un precio máximo de 3 €. ¿Qué ocurre?',
    opciones: ['No tiene efecto porque el precio de equilibrio es inferior a 3 €', 'Hay un exceso de oferta de 175 bocadillos', 'Hay un exceso de demanda de 125 bocadillos', 'El mercado alcanza el equilibrio a ese precio'],
    correcta: 2,
    explicacion: 'Con P = 3 €: Qd = 500 − 300 = 200; Qo = 75. Exceso de demanda = 200 − 75 = 125 bocadillos. El precio máximo de 3 € es vinculante porque está por debajo del equilibrio (4 €).',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 2,
    enunciado: 'Suben el precio de las motos y bajan los salarios de los mecánicos. ¿Qué ocurre con el precio y la cantidad de equilibrio de los coches (sustitutivos de las motos)?',
    opciones: ['No sabemos qué ocurrirá con precio ni con cantidad', 'Aumenta la cantidad, pero no sabemos qué pasará con el precio', 'Disminuye el precio y aumenta la cantidad', 'Aumentan tanto precio como cantidad'],
    correcta: 1,
    explicacion: 'El encarecimiento de motos desplaza la demanda de coches a la derecha (sube precio y cantidad). Los menores salarios de mecánicos bajan costes de reparación de coches, pudiendo desplazar la demanda de coches también a la derecha. El aumento de cantidad es seguro, pero el precio depende de efectos adicionales sobre la oferta de coches.',
  },
  {
    bloque: 'oferta-demanda',
    nivel: 3,
    enunciado: 'La elasticidad precio de la demanda de un bien es −2. Si el precio sube un 5 %, ¿cuánto cambia la cantidad demandada?',
    opciones: ['Sube un 10 %', 'Baja un 2,5 %', 'Baja un 10 %', 'Sube un 2,5 %'],
    correcta: 2,
    explicacion: 'Ed = %ΔQ / %ΔP → −2 = %ΔQ / 5 → %ΔQ = −10 %. La cantidad demandada cae un 10 %, lo que indica una demanda elástica.',
  },

  // ─── PUNTO MUERTO (Producción, costes y umbral de rentabilidad) ─────────────

  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'El punto muerto o umbral de rentabilidad es el nivel de producción en el que:',
    opciones: ['Se maximiza el beneficio', 'Solo se cubren los costes fijos', 'Los ingresos totales igualan a los costes totales (beneficio = 0)', 'Los costes variables son cero'],
    correcta: 2,
    explicacion: 'En el punto muerto (umbral de rentabilidad), IT = CT, es decir, el beneficio es exactamente cero. Por encima de ese punto la empresa empieza a obtener beneficios.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Una empresa tiene costes fijos de 1.000 € y costes variables de 2 € por balón. Si vende los balones a 3 € cada uno, ¿cuántos balones debe vender para alcanzar el punto muerto?',
    opciones: ['500 balones', '1.000 balones', '333 balones', '2.000 balones'],
    correcta: 1,
    explicacion: 'Umbral = CF / (P − Cv) = 1.000 / (3 − 2) = 1.000 balones. A partir de esa cantidad empieza a haber beneficios.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Una empresa produce 1.000 balones con costes fijos de 1.000 € y costes variables de 2 €/ud. Los vende a 3 €/ud. ¿Cuál es el beneficio?',
    opciones: ['0 €', '500 €', '1.000 €', '2.000 €'],
    correcta: 0,
    explicacion: 'IT = 3 × 1.000 = 3.000 €; CT = 1.000 + 2 × 1.000 = 3.000 €; Beneficio = IT − CT = 0 €. La empresa está exactamente en el punto muerto.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'Si una empresa no produce nada, sus pérdidas serán iguales a:',
    opciones: ['Cero, porque no hay producción', 'Sus costes variables totales', 'Sus costes fijos totales', 'Sus ingresos totales esperados'],
    correcta: 2,
    explicacion: 'Los costes fijos se incurren independientemente de la producción. Si la empresa produce cero unidades, IT = 0 y CT = CF, por lo que pierde exactamente sus costes fijos.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'Una empresa produce 5 pantalones con costes fijos de 1.000 € y costes variables de 100 €/unidad. Sus costes fijos totales son:',
    opciones: ['500 €', '1.500 €', '1.000 €', '2.000 €'],
    correcta: 2,
    explicacion: 'Los costes fijos no varían con la producción: siguen siendo 1.000 € independientemente de cuántos pantalones se fabriquen.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'El coste marginal es:',
    opciones: ['El coste total dividido entre las unidades producidas', 'El coste de producir la última unidad adicional', 'Los costes fijos totales', 'La diferencia entre ingresos y costes variables'],
    correcta: 1,
    explicacion: 'El coste marginal (Cmg) mide el incremento en el coste total al producir una unidad más: Cmg = ΔCT / ΔQ.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Si al producir una unidad más el coste marginal baja:',
    opciones: ['La empresa es menos productiva', 'La empresa está siendo más productiva (rendimientos crecientes)', 'El coste total siempre será menor', 'No podemos deducir nada sobre la productividad'],
    correcta: 1,
    explicacion: 'Un coste marginal decreciente indica que la productividad marginal del factor variable está aumentando, es decir, la empresa obtiene más producto por cada unidad adicional de input.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 3,
    enunciado: 'Una empresa transportista tiene como coste variable principal:',
    opciones: ['El Impuesto sobre Bienes Inmuebles del local', 'El seguro anual de los vehículos', 'El combustible consumido en cada ruta', 'La amortización de los camiones'],
    correcta: 2,
    explicacion: 'El combustible varía directamente con los kilómetros recorridos (producción). IBI, seguros y amortización son costes fijos que no dependen del volumen de servicio prestado.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Si el precio de venta de un bien es inferior a su coste marginal de producir una unidad más:',
    opciones: ['El beneficio aumenta al producir esa unidad', 'El beneficio disminuye al producir esa unidad', 'El beneficio no cambia', 'Los ingresos siempre bajarán'],
    correcta: 1,
    explicacion: 'Si P < Cmg, producir una unidad adicional añade menos ingresos que costes, reduciendo el beneficio. La empresa maximiza beneficio cuando P = Cmg.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 3,
    enunciado: 'Una empresa tiene CF = 2.000 €, Cv = 5 € por unidad y precio de venta P = 9 €. ¿Cuántas unidades debe vender para tener un beneficio de 2.000 €?',
    opciones: ['500 unidades', '1.000 unidades', '750 unidades', '400 unidades'],
    correcta: 1,
    explicacion: 'Beneficio = (P − Cv) × Q − CF → 2.000 = (9 − 5) × Q − 2.000 → 4Q = 4.000 → Q = 1.000 unidades.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 1,
    enunciado: 'Los costes directos de producción son aquellos que:',
    opciones: ['Son independientes del volumen de producción', 'Se asignan de forma clara e inequívoca a cada producto fabricado', 'Necesitan criterios de reparto para distribuirlos entre productos', 'Coinciden siempre con los costes fijos'],
    correcta: 1,
    explicacion: 'Los costes directos son perfectamente identificables y atribuibles a un producto concreto sin necesidad de criterios de asignación arbitrarios.',
  },
  {
    bloque: 'punto-muerto',
    nivel: 2,
    enunciado: 'Una empresa con rendimientos decrecientes a escala dobla todos sus factores de producción. Su producción:',
    opciones: ['Se dobla exactamente', 'Aumenta más del doble', 'Aumenta menos del doble', 'Se mantiene igual'],
    correcta: 2,
    explicacion: 'Con rendimientos decrecientes a escala, un aumento proporcional de todos los factores genera un incremento de producción proporcionalmente menor.',
  },

  // ─── POLÍTICA ECONÓMICA (Monetaria y fiscal) ──────────────────────────────

  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'Para Keynes, la medida más adecuada durante una crisis económica es:',
    opciones: ['Reducir el gasto público para equilibrar el presupuesto', 'Subir los tipos de interés para frenar la inflación', 'Llevar a cabo una política fiscal expansiva (aumentar gasto o reducir impuestos)', 'Dejar que el mercado se corrija solo a largo plazo'],
    correcta: 2,
    explicacion: 'Keynes defendió que en recesiones el Estado debe estimular la demanda agregada mediante aumentos del gasto público o reducciones de impuestos, no esperar al ajuste automático del mercado.',
  },
  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'Si el Estado aumenta los impuestos y reduce el gasto público, está aplicando una política fiscal:',
    opciones: ['Expansiva', 'Contractiva (restrictiva)', 'Monetaria', 'De oferta'],
    correcta: 1,
    explicacion: 'Una política fiscal contractiva (también llamada restrictiva) retira recursos de la economía mediante más impuestos y/o menos gasto público, buscando enfriar la demanda y reducir la inflación.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'Cuando el Estado lleva una política fiscal contractiva, es probable que:',
    opciones: ['El PIB suba y el desempleo baje', 'El PIB baje y el desempleo suba', 'Los precios suban por la mayor demanda', 'El BCE suba automáticamente los tipos de interés'],
    correcta: 1,
    explicacion: 'Al retirar demanda agregada, la política fiscal contractiva tiende a reducir la producción y el empleo, aunque también modera la inflación.',
  },
  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'Las políticas de oferta buscan principalmente:',
    opciones: ['Aumentar el consumo privado a corto plazo', 'Mejorar la productividad y la capacidad productiva de la economía a largo plazo', 'Subir los salarios de los trabajadores de forma directa', 'Aumentar el déficit público para estimular la economía'],
    correcta: 1,
    explicacion: 'Las políticas de oferta actúan sobre los factores de producción y la eficiencia del mercado (educación, I+D, flexibilidad laboral) con el objetivo de aumentar la producción potencial a largo plazo.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'Uno de los problemas del déficit y la deuda pública crecientes es:',
    opciones: ['Que se genera siempre con políticas fiscales contractivas', 'Que obliga a pagar elevados intereses en el futuro, limitando el gasto público disponible', 'Que reduce directamente la inflación del país', 'Que disminuye la prima de riesgo del país'],
    correcta: 1,
    explicacion: 'Un elevado déficit acumulado genera deuda pública que requiere el pago de intereses crecientes, reduciendo el margen para otras políticas y aumentando la prima de riesgo si se pierde confianza.',
  },
  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'Cuando el BCE sube los tipos de interés, el objetivo principal es:',
    opciones: ['Estimular la inversión empresarial', 'Aumentar el consumo de las familias', 'Reducir la inflación enfriando el crédito y la demanda', 'Financiar el déficit de los países de la zona euro'],
    correcta: 2,
    explicacion: 'Tipos de interés más altos encarecen el crédito, reducen el consumo y la inversión, y así moderan la demanda agregada y la inflación. Es el principal instrumento de política monetaria contractiva del BCE.',
  },
  {
    bloque: 'politica-economica',
    nivel: 3,
    enunciado: 'Un banco recibe un depósito de 10.000 € y el coeficiente de caja es del 10 %. ¿Cuánto dinero puede crear el sistema bancario a través del multiplicador del dinero?',
    opciones: ['10.000 €', '100.000 €', '90.000 €', '11.000 €'],
    correcta: 1,
    explicacion: 'El multiplicador del dinero = 1 / coeficiente de caja = 1 / 0,10 = 10. Dinero total creado = 10.000 × 10 = 100.000 €. La banca de reserva fraccional amplifica los depósitos iniciales.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'En un período de expansión económica intensa, lo más habitual es que:',
    opciones: ['El desempleo suba y los precios bajen', 'El desempleo baje y los precios suban (riesgo inflacionario)', 'Tanto el desempleo como los precios bajen', 'El PIB caiga y la inversión aumente'],
    correcta: 1,
    explicacion: 'Durante una expansión, la demanda supera la oferta: el empleo crece (menor desempleo) y los precios tienden a subir por las presiones inflacionarias.',
  },
  {
    bloque: 'politica-economica',
    nivel: 1,
    enunciado: 'La macroeconomía estudia principalmente:',
    opciones: ['Por qué sube el precio de los tomates en un mercado local', 'Los costes de producción de una empresa individual', 'Variables agregadas como el PIB, el desempleo y la inflación de un país', 'Las decisiones de consumo de una familia concreta'],
    correcta: 2,
    explicacion: 'La macroeconomía analiza la economía en su conjunto: producción total (PIB), nivel general de precios, tasa de desempleo y relaciones entre grandes sectores, a diferencia de la microeconomía que analiza agentes individuales.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'En el cálculo del PIB por el método del gasto, ¿cuál de las siguientes partidas se suma al PIB español?',
    opciones: ['Lo que un español produce en Francia', 'Lo que produce un inglés residente en España', 'Lo que una empresa española compra como input a una empresa italiana', 'Las exportaciones netas de España'],
    correcta: 1,
    explicacion: 'El PIB mide la producción realizada dentro del territorio, independientemente de la nacionalidad. Un inglés que trabaja en España genera producción que se incluye en el PIB español.',
  },
  {
    bloque: 'politica-economica',
    nivel: 3,
    enunciado: 'Una empresa obtiene madera del bosque y la vende por 5.000 € a otra empresa que fabrica armarios valorados en 9.000 € y los vende a otra que los transforma en mesas vendidas a 12.000 €. ¿En cuánto sube el PIB por estas transacciones?',
    opciones: ['26.000 €', '12.000 €', '21.000 €', '7.000 €'],
    correcta: 1,
    explicacion: 'El PIB por el método del valor añadido suma solo el valor añadido en cada etapa, evitando la doble contabilización. Valor añadido total = 5.000 + (9.000 − 5.000) + (12.000 − 9.000) = 12.000 €.',
  },
  {
    bloque: 'politica-economica',
    nivel: 2,
    enunciado: 'Hay inflación cuando:',
    opciones: ['Sube el precio de un bien concreto', 'Sube el nivel general de precios de forma sostenida en el tiempo', 'Suben los precios solo en un mes puntual', 'Baja el poder adquisitivo de forma puntual'],
    correcta: 1,
    explicacion: 'La inflación requiere que sea un fenómeno generalizado (afecte a la mayoría de bienes y servicios) y sostenido en el tiempo. Una subida puntual o de un solo producto no es inflación.',
  },
  {
    bloque: 'politica-economica',
    nivel: 3,
    enunciado: 'El IPC en 2020 era 109, en 2021 era 105 y en 2022 era 115 (base 2015 = 100). La tasa de inflación interanual entre 2021 y 2022 es aproximadamente:',
    opciones: ['−3,7 %', '+9,5 %', '+5,5 %', '+3,2 %'],
    correcta: 1,
    explicacion: 'Tasa inflación 21-22 = (IPC₂₂ − IPC₂₁) / IPC₂₁ × 100 = (115 − 105) / 105 × 100 ≈ 9,52 %. Un fuerte repunte inflacionario en ese período.',
  },

  // ─── MERCADO DE TRABAJO ───────────────────────────────────────────────────

  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'El desempleo estructural se produce cuando:',
    opciones: ['Hay una recesión económica que reduce la demanda de trabajo', 'Hay desajuste entre las cualificaciones de los trabajadores y los puestos disponibles', 'Los trabajadores se encuentran entre dos empleos temporalmente', 'La demanda de trabajo varía según la época del año'],
    correcta: 1,
    explicacion: 'El desempleo estructural surge cuando la oferta y demanda de trabajo no se ajustan cualitativamente: hay vacantes sin cubrir y desempleados que no tienen las habilidades requeridas.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'Un país tiene 5 millones de desempleados, tasa de paro del 25 % y tasa de actividad del 50 %. ¿Cuál es su población en edad de trabajar?',
    opciones: ['12,5 millones', '20 millones', '40 millones', '10 millones'],
    correcta: 2,
    explicacion: 'Tasa paro = desempleados / activos → 0,25 = 5M / activos → activos = 20M. Tasa actividad = activos / PET → 0,50 = 20M / PET → PET = 40 millones.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'Ismael ha dejado su trabajo para tomarse un año sabático. Ismael pertenece a:',
    opciones: ['La población activa desempleada', 'La población ocupada', 'La población inactiva', 'La población activa en búsqueda de empleo'],
    correcta: 2,
    explicacion: 'Una persona que no trabaja y no busca empleo activamente pertenece a la población inactiva (estudiantes, jubilados, personas que se dedican al hogar, etc.).',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'El desempleo friccional:',
    opciones: ['Es muy preocupante porque indica una crisis estructural', 'Es inevitable y transitorio (personas entre empleos o buscando su primer trabajo)', 'Se produce por desajustes de cualificación', 'Se debe a la estacionalidad de ciertos sectores'],
    correcta: 1,
    explicacion: 'El paro friccional existe siempre en toda economía dinámica: refleja el tiempo que tardan las personas en encontrar un nuevo empleo al cambiar de trabajo o al incorporarse al mercado laboral.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 2,
    enunciado: 'La Encuesta de Población Activa (EPA):',
    opciones: ['Cuenta las personas que han cobrado prestación por desempleo en el último año', 'Suele arrojar datos de parados más bajos que el SEPE y es el instrumento usado para comparaciones internacionales', 'Registra a todos los parados inscritos en las oficinas de empleo', 'La realiza el SEPE trimestralmente'],
    correcta: 1,
    explicacion: 'La EPA (elaborada por el INE) utiliza criterios OIT, lo que incluye toda búsqueda activa de empleo, resultando habitualmente en cifras de paro menores que el registro del SEPE. Es el indicador oficial para comparaciones de Eurostat.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'Las políticas pasivas de empleo buscan:',
    opciones: ['Crear puestos de trabajo directamente', 'Mejorar la formación de los desempleados', 'Proporcionar ayudas económicas a las personas desempleadas (subsidios, prestaciones)', 'Reducir el desempleo friccional mediante bolsas de empleo'],
    correcta: 2,
    explicacion: 'Las políticas pasivas son medidas de protección económica (prestaciones por desempleo, subsidios) que ayudan a los parados mientras buscan trabajo, sin actuar directamente sobre la creación de empleo.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 2,
    enunciado: 'Una persona acaba de ser despedida y busca activamente un nuevo trabajo. Está en situación de:',
    opciones: ['Desempleo estructural', 'Desempleo estacional', 'Desempleo friccional', 'Población inactiva'],
    correcta: 2,
    explicacion: 'El desempleo friccional incluye a personas que han perdido o dejado su empleo y están en proceso de búsqueda de uno nuevo; es un desempleo temporal y de transición.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 2,
    enunciado: 'Una persona que busca activamente trabajo pero no lo encuentra se considera:',
    opciones: ['Inactiva', 'Solo activa', 'Desempleada (activa desempleada)', 'Ocupada a tiempo parcial'],
    correcta: 2,
    explicacion: 'Según la OIT, una persona está desempleada si no tiene trabajo, está disponible para trabajar y busca activamente empleo. Pertenece a la población activa pero en su componente desempleado.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 3,
    enunciado: 'El desempleo cíclico o coyuntural se produce principalmente cuando:',
    opciones: ['La economía experimenta una recesión y la demanda de trabajo cae', 'Los trabajadores cambian de empleo voluntariamente', 'Las habilidades de los trabajadores no coinciden con las demandas del mercado', 'La producción agrícola baja fuera de temporada'],
    correcta: 0,
    explicacion: 'El paro cíclico o keynesiano refleja la caída en la demanda agregada durante las recesiones: las empresas producen menos y despiden trabajadores. Se corrige con políticas expansivas que reactiven la economía.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 1,
    enunciado: 'Los efectos del desempleo incluyen:',
    opciones: ['Reducción del gasto público del Estado', 'Solo efectos negativos para las empresas', 'Estrés y ansiedad social, familias en situación precaria y mayor gasto estatal en prestaciones', 'Aumento de la productividad por la competencia laboral'],
    correcta: 2,
    explicacion: 'El desempleo tiene costes humanos (deterioro psicológico, pobreza), sociales (aumento de desigualdad) y fiscales (más gasto en prestaciones, menos recaudación fiscal).',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 3,
    enunciado: 'En España se puede empezar a trabajar desde los:',
    opciones: ['15 años sin restricciones', '18 años como mínimo en todo caso', '16 años con autorización del tutor legal; nunca antes', '14 años si hay autorización judicial'],
    correcta: 2,
    explicacion: 'El Estatuto de los Trabajadores fija los 16 años como la edad mínima para trabajar en España, siempre con autorización del representante legal si el menor no está emancipado.',
  },
  {
    bloque: 'mercado-trabajo',
    nivel: 2,
    enunciado: 'Un convenio colectivo es:',
    opciones: ['Un pacto entre trabajadores para aumentar la producción', 'Un acuerdo entre representantes de trabajadores y empresarios para regular condiciones laborales', 'Un acuerdo entre asociaciones empresariales para fijar salarios', 'Una ley aprobada por el Parlamento sobre condiciones de trabajo'],
    correcta: 1,
    explicacion: 'Los convenios colectivos son acuerdos negociados entre sindicatos (representantes de trabajadores) y patronales (representantes empresariales) que fijan salarios, jornada, vacaciones y otras condiciones laborales.',
  },

  // ─── ESTRUCTURAS DE MERCADO ───────────────────────────────────────────────

  {
    bloque: 'estructuras-mercado',
    nivel: 1,
    enunciado: '¿Cuántas empresas hay en un mercado de competencia perfecta?',
    opciones: ['Una sola empresa que domina el mercado', 'Dos o tres grandes empresas', 'Muchas empresas que venden un producto homogéneo', 'Pocas empresas que venden productos diferenciados'],
    correcta: 2,
    explicacion: 'La competencia perfecta requiere muchos vendedores y compradores con productos idénticos (homogéneos), de modo que ninguno puede influir en el precio de mercado.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 1,
    enunciado: 'En un monopolio, la empresa es «precio-aceptante» porque:',
    opciones: ['Acepta el precio que fija el Estado', 'Acepta el precio que fija el mercado al haber mucha competencia', 'No; en un monopolio la empresa es «precio-fijadora» (price-maker)', 'El precio lo fija la demanda sin que la empresa pueda influir'],
    correcta: 2,
    explicacion: 'Es al contrario: en competencia perfecta las empresas son precio-aceptantes. En un monopolio la empresa es precio-fijadora porque es la única oferente y puede elegir el precio maximizador de beneficios.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 1,
    enunciado: '¿Cuál de las siguientes es una característica del oligopolio?',
    opciones: ['Muchas empresas con productos homogéneos', 'Una sola empresa que vende un producto sin sustitutivos', 'Pocas empresas que son conscientes de su interdependencia y vigilan sus decisiones mutuas', 'Libre entrada y salida sin barreras'],
    correcta: 2,
    explicacion: 'El oligopolio se caracteriza por pocos vendedores interdependientes: cada empresa decide teniendo en cuenta las reacciones probables de sus rivales (interdependencia estratégica).',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 1,
    enunciado: 'La competencia monopolística se parece a la competencia perfecta en que:',
    opciones: ['Los productos son homogéneos', 'Las empresas tienen poder de mercado ilimitado', 'Hay muchas empresas y libre entrada/salida', 'Las empresas obtienen beneficios extraordinarios a largo plazo'],
    correcta: 2,
    explicacion: 'En competencia monopolística hay muchos vendedores y libre entrada. Se diferencia de la perfecta en que cada empresa vende un producto diferenciado, lo que le otorga cierto poder sobre el precio.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 2,
    enunciado: 'Una empresa en competencia perfecta maximiza beneficios cuando:',
    opciones: ['El ingreso total es máximo', 'El precio iguala al coste medio', 'El ingreso marginal iguala al coste marginal (IMg = CMg)', 'El coste marginal es cero'],
    correcta: 2,
    explicacion: 'La regla general de maximización de beneficios es IMg = CMg. En competencia perfecta IMg = P, por lo que la condición se convierte en P = CMg.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 2,
    enunciado: 'Un monopolista con demanda P = 100 − Q tiene costes marginales constantes CMg = 20. ¿A qué precio y cantidad maximiza beneficios?',
    opciones: ['P = 20; Q = 80', 'P = 60; Q = 40', 'P = 40; Q = 60', 'P = 80; Q = 20'],
    correcta: 1,
    explicacion: 'IMg = 100 − 2Q (derivada del ingreso total P × Q = 100Q − Q²). IMg = CMg → 100 − 2Q = 20 → Q = 40. P = 100 − 40 = 60. El monopolista fija P = 60 y Q = 40.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 2,
    enunciado: 'El peso muerto (pérdida irrecuperable de eficiencia) del monopolio representa:',
    opciones: ['El beneficio extra que obtiene el monopolista', 'La pérdida de excedente total (consumidores + productores) respecto al equilibrio competitivo', 'El impuesto que paga el monopolista al Estado', 'El coste de producción que no puede recuperar'],
    correcta: 1,
    explicacion: 'El monopolista produce menos que el nivel competitivo (donde P = CMg), generando una pérdida de bienestar social neto denominada peso muerto o carga de eficiencia del monopolio.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 2,
    enunciado: '¿Qué ocurre a largo plazo con los beneficios extraordinarios en competencia monopolística?',
    opciones: ['Aumentan porque la empresa tiene poder de mercado', 'Se mantienen indefinidamente igual que en el monopolio', 'Desaparecen porque la entrada de nuevas empresas erosiona esos beneficios', 'Desaparecen porque el Estado los regula directamente'],
    correcta: 2,
    explicacion: 'En competencia monopolística la libre entrada atrae rivales cuando hay beneficios extraordinarios, aumentando la oferta y reduciendo los precios hasta que el beneficio económico se anula a largo plazo.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 3,
    enunciado: 'En competencia perfecta el precio de largo plazo se sitúa en el mínimo del coste medio porque:',
    opciones: ['El gobierno fija ese precio por ley', 'Las empresas con costes más altos entran al mercado y bajan el precio', 'La libre entrada y salida elimina los beneficios extraordinarios: solo sobreviven empresas en el mínimo eficiente de escala', 'El coste marginal es siempre creciente'],
    correcta: 2,
    explicacion: 'Si hay beneficios, entran empresas → precio baja. Si hay pérdidas, salen empresas → precio sube. El equilibrio de largo plazo se da cuando P = CMg = CMe (mínimo), con beneficio económico nulo.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 3,
    enunciado: 'Comparando monopolio y competencia perfecta con la misma demanda y costes, el monopolio produce:',
    opciones: ['Mayor cantidad y menor precio que el mercado competitivo', 'Menor cantidad y mayor precio que el mercado competitivo', 'Igual cantidad pero mayor precio', 'Mayor cantidad y mayor precio'],
    correcta: 1,
    explicacion: 'El monopolista maximiza beneficios en IMg = CMg, lo que le lleva a restringir la producción por debajo del nivel competitivo (P = CMg) para elevar el precio por encima del coste marginal.',
  },
  {
    bloque: 'estructuras-mercado',
    nivel: 3,
    enunciado: 'Una empresa oligopolista se plantea si bajar el precio. Según la curva de demanda quebrada (modelo Sweezy), si baja el precio:',
    opciones: ['Los rivales también bajarán y ganará cuota de mercado', 'Los rivales no reaccionan y la empresa gana mucha cuota de mercado', 'Los rivales también bajarán, por lo que el beneficio de bajar el precio es escaso', 'El gobierno intervendrá para impedir la guerra de precios'],
    correcta: 2,
    explicacion: 'En el modelo de demanda quebrada, si una empresa baja el precio los rivales la imitan (también bajan), de modo que la cuota de mercado cambia poco y los ingresos disminuyen: la empresa tiene pocos incentivos para reducir el precio.',
  },

  // ─── MACRO-MAGNITUDES ─────────────────────────────────────────────────────

  {
    bloque: 'macro-magnitudes',
    nivel: 1,
    enunciado: 'El PIB se define como:',
    opciones: ['El valor de todos los bienes producidos por empresas nacionales, dentro y fuera del país', 'El valor monetario de todos los bienes y servicios finales producidos dentro de un país en un período dado', 'La suma de los salarios pagados a los trabajadores residentes en el país', 'El valor de los bienes intermedios y finales producidos en el país'],
    correcta: 1,
    explicacion: 'El PIB mide el valor de la producción final (no intermedia) generada en el territorio nacional en un período, independientemente de la nacionalidad de quien produce.',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 1,
    enunciado: '¿Cuál de los tres métodos del PIB NO existe?',
    opciones: ['Método del gasto (demanda agregada)', 'Método de la renta (suma de rentas factoriales)', 'Método del ahorro (suma de ahorros de los sectores)', 'Método del valor añadido (suma de VA en cada etapa)'],
    correcta: 2,
    explicacion: 'Los tres métodos oficiales para calcular el PIB son: gasto (C + I + G + XN), renta (suma de salarios, beneficios, intereses y rentas) y valor añadido (suma del VA de cada sector). El «método del ahorro» no existe.',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 1,
    enunciado: 'La diferencia entre PIB nominal y PIB real es que:',
    opciones: ['El PIB real incluye los servicios y el nominal solo los bienes', 'El PIB nominal usa precios del año base y el real usa precios corrientes', 'El PIB real mide la producción a precios constantes (descuenta la inflación); el nominal usa precios corrientes', 'No hay diferencia: son la misma magnitud'],
    correcta: 2,
    explicacion: 'El PIB nominal se valora a precios del año en curso (incluye el efecto de la inflación). El PIB real se valora a precios de un año base, permitiendo comparar el crecimiento efectivo de la producción.',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 2,
    enunciado: 'Si el PIB nominal es 500.000 M€ y el deflactor del PIB es 125, ¿cuál es el PIB real?',
    opciones: ['625.000 M€', '375.000 M€', '400.000 M€', '500.000 M€'],
    correcta: 2,
    explicacion: 'PIB real = PIB nominal / deflactor × 100 = 500.000 / 125 × 100 = 400.000 M€. El deflactor mide el nivel general de precios respecto al año base (100).',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 2,
    enunciado: 'El IPC en enero de 2023 era 108 y en enero de 2024 era 113,4 (base 2021 = 100). La tasa de inflación interanual es:',
    opciones: ['5,0 %', '5,4 %', '4,6 %', '13,4 %'],
    correcta: 0,
    explicacion: 'Tasa de inflación = (IPC₂₄ − IPC₂₃) / IPC₂₃ × 100 = (113,4 − 108) / 108 × 100 = 5,4 / 108 × 100 = 5,0 %. La inflación interanual fue del 5,0 %.',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 2,
    enunciado: '¿Qué fase del ciclo económico se caracteriza por crecimiento del PIB, aumento del empleo y subida de precios?',
    opciones: ['Recesión', 'Depresión', 'Expansión', 'Contracción'],
    correcta: 2,
    explicacion: 'En la fase de expansión la producción crece por encima de la tendencia, el desempleo cae y los precios tienden a subir por las presiones de demanda sobre una economía que se acerca al pleno empleo.',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 1,
    enunciado: 'La tasa de crecimiento del PIB real se calcula como:',
    opciones: ['(PIB nominal actual − PIB nominal anterior) / PIB nominal anterior × 100', '(PIB real actual − PIB real anterior) / PIB real anterior × 100', 'PIB real × deflactor / 100', '(Exportaciones − Importaciones) / PIB real × 100'],
    correcta: 1,
    explicacion: 'La tasa de crecimiento económico real compara el PIB real de dos períodos consecutivos para medir el incremento efectivo de la producción, descartando el efecto de la inflación.',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 2,
    enunciado: 'La deflación es:',
    opciones: ['Una inflación superior al 10 % anual', 'Una caída generalizada y sostenida del nivel de precios', 'La reducción del déficit público', 'Una bajada del tipo de interés del BCE'],
    correcta: 1,
    explicacion: 'La deflación es una bajada generalizada y persistente de los precios (tasa de inflación negativa). Aunque parece positiva para los consumidores, puede generar una espiral recesiva al posponer decisiones de compra e inversión.',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 3,
    enunciado: 'Si el PIB nominal crece un 8 % y la inflación es del 5 %, ¿en qué porcentaje aproximado creció el PIB real?',
    opciones: ['13 %', '8 %', '3 %', '5 %'],
    correcta: 2,
    explicacion: 'Aproximación: crecimiento real ≈ crecimiento nominal − inflación = 8 % − 5 % = 3 %. (El cálculo exacto da (1,08 / 1,05 − 1) × 100 ≈ 2,86 %, prácticamente 3 %.)',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 3,
    enunciado: 'La economía de un país produce solo manzanas: en 2022 produjo 1.000 kg a 2 €/kg; en 2023 produjo 1.100 kg a 2,2 €/kg. Tomando 2022 como año base, el PIB real de 2023 es:',
    opciones: ['2.420 €', '2.200 €', '2.000 €', '1.100 €'],
    correcta: 1,
    explicacion: 'PIB real 2023 = cantidad 2023 × precio año base = 1.100 kg × 2 €/kg = 2.200 €. El deflactor de 2023 sería 2,2 / 2 × 100 = 110; PIB nominal = 2.420 €.',
  },
  {
    bloque: 'macro-magnitudes',
    nivel: 1,
    enunciado: 'El Índice de Precios al Consumo (IPC) mide:',
    opciones: ['El nivel de precios de todos los bienes producidos en el país', 'La evolución del coste de una cesta representativa de bienes y servicios consumidos por los hogares', 'La variación del precio de los bienes de inversión', 'El precio de las exportaciones de un país'],
    correcta: 1,
    explicacion: 'El IPC sigue la evolución del coste de una «cesta de la compra» representativa del consumo de las familias, y es el indicador más usado para medir la inflación que afecta al poder adquisitivo de los hogares.',
  },

  // ─── SISTEMA FINANCIERO ───────────────────────────────────────────────────

  {
    bloque: 'sistema-financiero',
    nivel: 1,
    enunciado: '¿Cuáles son las tres funciones clásicas del dinero?',
    opciones: ['Reserva de valor, medio de pago y unidad de cuenta', 'Crédito, ahorro e inversión', 'Liquidez, rentabilidad y solvencia', 'Depósito, préstamo y transferencia'],
    correcta: 0,
    explicacion: 'El dinero cumple tres funciones: medio de pago (facilita el intercambio), unidad de cuenta (permite comparar valores) y reserva de valor (permite guardar poder adquisitivo para el futuro).',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 1,
    enunciado: 'El sistema bancario de reserva fraccionaria consiste en que los bancos:',
    opciones: ['Guardan el 100 % de los depósitos en sus cajas de seguridad', 'Prestan todo el dinero depositado sin retener nada', 'Solo guardan una fracción de los depósitos como reserva y prestan el resto', 'Invierten todos los depósitos en activos del Estado'],
    correcta: 2,
    explicacion: 'En la banca de reserva fraccionaria los bancos solo mantienen un porcentaje mínimo (coeficiente de caja) del total depositado, prestando el resto y creando dinero bancario de forma endógena.',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 2,
    enunciado: 'Si el coeficiente de caja es del 4 %, ¿cuál es el multiplicador del dinero?',
    opciones: ['4', '0,04', '25', '40'],
    correcta: 2,
    explicacion: 'Multiplicador del dinero = 1 / coeficiente de caja = 1 / 0,04 = 25. Cada euro de base monetaria puede llegar a generar hasta 25 euros de dinero bancario en el sistema.',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 2,
    enunciado: 'Un banco recibe un depósito inicial de 5.000 € y el coeficiente de caja es del 5 %. ¿Cuánto dinero puede crear el sistema bancario en total (incluyendo el depósito inicial)?',
    opciones: ['5.250 €', '25.000 €', '100.000 €', '4.750 €'],
    correcta: 2,
    explicacion: 'Multiplicador = 1 / 0,05 = 20. Dinero total = depósito inicial × multiplicador = 5.000 × 20 = 100.000 €.',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 1,
    enunciado: 'El agregado monetario M1 incluye principalmente:',
    opciones: ['Solo las monedas y billetes en circulación fuera de los bancos', 'El efectivo en manos del público más los depósitos a la vista (cuentas corrientes)', 'Los depósitos a plazo fijo y los fondos de inversión monetarios', 'Todos los activos financieros líquidos del sistema'],
    correcta: 1,
    explicacion: 'M1 es la definición más estricta de dinero: efectivo en circulación (billetes y monedas) más los depósitos a la vista (cuentas corrientes transferibles). M2 y M3 añaden activos progresivamente menos líquidos.',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 2,
    enunciado: 'Cuando el BCE sube los tipos de interés de referencia, ¿qué ocurre con el precio de los bonos ya emitidos?',
    opciones: ['Sube, porque los bonos son más atractivos', 'No varía porque el cupón ya está fijado', 'Baja, porque los bonos existentes son menos atractivos frente a los nuevos a mayor tipo', 'Sube solo si son bonos del Estado'],
    correcta: 2,
    explicacion: 'Existe una relación inversa entre tipo de interés y precio de los bonos: cuando suben los tipos, los nuevos bonos ofrecen más rentabilidad, por lo que los bonos viejos (con cupón más bajo) caen de precio para competir.',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 2,
    enunciado: 'Una política monetaria expansiva llevada a cabo por el BCE consiste en:',
    opciones: ['Subir los tipos de interés para frenar el crédito', 'Vender bonos en el mercado para retirar dinero en circulación', 'Bajar los tipos de interés y/o comprar activos para aumentar la liquidez', 'Aumentar el coeficiente de caja de los bancos comerciales'],
    correcta: 2,
    explicacion: 'La política monetaria expansiva busca estimular la economía aumentando la oferta monetaria: bajando tipos de interés (facilita el crédito) y/o comprando activos en el mercado abierto (inyecta liquidez).',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 1,
    enunciado: 'La prima de riesgo de un país se define como:',
    opciones: ['El tipo de interés que paga el BCE a los bancos comerciales', 'La diferencia entre el tipo de interés de su bono a 10 años y el del bono alemán (bund)', 'El porcentaje de impagos de los préstamos hipotecarios', 'El diferencial entre tipos de depósito y de préstamo de los bancos'],
    correcta: 1,
    explicacion: 'La prima de riesgo mide el sobrecoste que paga un país por financiarse respecto al emisor de referencia (Alemania). Sube cuando los inversores perciben mayor riesgo de impago soberano.',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 3,
    enunciado: 'Si el BCE sube el coeficiente de caja del 2 % al 4 %, ¿qué ocurre con el multiplicador del dinero?',
    opciones: ['Sube de 50 a 25', 'Baja de 50 a 25', 'Se mantiene igual', 'Sube de 25 a 50'],
    correcta: 1,
    explicacion: 'Con coeficiente 2 %: multiplicador = 1 / 0,02 = 50. Con coeficiente 4 %: multiplicador = 1 / 0,04 = 25. Al aumentar el coeficiente, los bancos prestan menos y el multiplicador baja, reduciendo la creación de dinero.',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 3,
    enunciado: 'Un bono con valor nominal de 1.000 € paga un cupón fijo de 40 € anuales. Si el tipo de interés de mercado sube al 5 %, ¿cuál será aproximadamente su precio de mercado?',
    opciones: ['1.000 €', '1.040 €', '800 €', '500 €'],
    correcta: 2,
    explicacion: 'El precio del bono se calcula como cupón / tipo de mercado = 40 / 0,05 = 800 €. Al subir los tipos, el bono existente cae de precio porque su cupón fijo es proporcionalmente menos atractivo.',
  },
  {
    bloque: 'sistema-financiero',
    nivel: 2,
    enunciado: 'Los agregados monetarios M1, M2 y M3 se ordenan de:',
    opciones: ['Mayor a menor liquidez (M1 es el más líquido)', 'Menor a mayor liquidez (M3 es el más líquido)', 'Mayor a menor volumen (M1 siempre tiene más saldo que M3)', 'Igual liquidez, solo difieren en el plazo'],
    correcta: 0,
    explicacion: 'M1 (efectivo + depósitos a la vista) es el más líquido; M2 añade depósitos a plazo corto; M3 incluye además participaciones en fondos del mercado monetario. Cada M amplía el anterior añadiendo activos menos líquidos.',
  },

  // ─── COMERCIO INTERNACIONAL ───────────────────────────────────────────────

  {
    bloque: 'comercio-internacional',
    nivel: 1,
    enunciado: 'La ventaja absoluta en la producción de un bien significa que:',
    opciones: ['Un país produce ese bien con menor coste de oportunidad que otro', 'Un país produce más unidades de ese bien que otro con los mismos recursos', 'Un país exporta más de ese bien que el resto del mundo', 'Un país tiene tecnología superior en todos los bienes'],
    correcta: 1,
    explicacion: 'La ventaja absoluta (Adam Smith) indica eficiencia técnica: un país tiene ventaja absoluta si, con la misma cantidad de recursos, produce más unidades que otro. La ventaja comparativa (Ricardo) se basa en el coste de oportunidad.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 1,
    enunciado: 'La ventaja comparativa determina en qué bien se debe especializar un país según:',
    opciones: ['En qué bien tiene mayor productividad absoluta', 'En qué bien tiene menor coste de oportunidad respecto al otro país', 'En qué bien tiene mayor demanda internacional', 'En qué bien tiene más recursos naturales'],
    correcta: 1,
    explicacion: 'Según David Ricardo, un país se especializa en el bien en el que su coste de oportunidad es más bajo en comparación con el otro país, aunque no tenga ventaja absoluta en ninguno.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 2,
    enunciado: 'España puede producir 10 coches o 20 naranjas por trabajador. Portugal puede producir 4 coches o 16 naranjas por trabajador. ¿Qué país tiene ventaja comparativa en naranjas?',
    opciones: ['España, porque produce más naranjas por trabajador en términos absolutos', 'Portugal, porque su coste de oportunidad de las naranjas es menor (0,25 coches) que el de España (0,5 coches)', 'España, porque su coste de oportunidad de las naranjas es mayor', 'Ninguno; los costes de oportunidad son iguales'],
    correcta: 1,
    explicacion: 'Coste de oportunidad de 1 naranja: España = 10/20 = 0,5 coches; Portugal = 4/16 = 0,25 coches. Portugal renuncia a menos coches por naranja → ventaja comparativa en naranjas.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 1,
    enunciado: 'La balanza de pagos de un país registra:',
    opciones: ['Solo las exportaciones e importaciones de bienes', 'Todas las transacciones económicas de un país con el resto del mundo durante un período', 'El saldo de la deuda pública del país con organismos internacionales', 'El tipo de cambio oficial fijado por el banco central'],
    correcta: 1,
    explicacion: 'La balanza de pagos es un registro estadístico de todas las transacciones económicas (bienes, servicios, rentas, transferencias y movimientos de capital) entre residentes del país y el resto del mundo.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 2,
    enunciado: 'Si un turista alemán gasta 1.000 € en hoteles españoles, esa transacción aparece en la balanza de pagos española como:',
    opciones: ['Importación de servicios turísticos en la balanza por cuenta corriente', 'Exportación de servicios turísticos en la balanza por cuenta corriente', 'Entrada de capital en la cuenta financiera', 'Transferencia en la cuenta de capital'],
    correcta: 1,
    explicacion: 'El turismo es una exportación de servicios: España «vende» servicios turísticos al extranjero. Los ingresos por turismo extranjero se registran como exportación en la cuenta corriente.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 2,
    enunciado: 'Un arancel es:',
    opciones: ['Una cuota que limita el volumen máximo de importaciones', 'Un impuesto que grava las importaciones y encarece los productos extranjeros', 'Una subvención a los exportadores nacionales', 'Un acuerdo bilateral de libre comercio'],
    correcta: 1,
    explicacion: 'Un arancel es un impuesto aplicado sobre los bienes importados, que eleva su precio en el mercado interior, protegiendo a los productores nacionales pero perjudicando a los consumidores.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 2,
    enunciado: 'Cuando la moneda nacional se aprecia (sube el tipo de cambio de la moneda local):',
    opciones: ['Las exportaciones se abaratan para el extranjero y las importaciones se encarecen', 'Las exportaciones se encarecen para el extranjero y las importaciones se abaratan', 'No afecta al comercio exterior porque el precio en moneda local no cambia', 'Mejora la balanza comercial al aumentar las exportaciones'],
    correcta: 1,
    explicacion: 'Una apreciación de la moneda nacional encarece los productos nacionales para los compradores extranjeros (exportaciones bajan) y abarata los productos extranjeros para los residentes (importaciones suben), tendiendo a deteriorar la balanza comercial.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 1,
    enunciado: 'El argumento de la «industria naciente» justifica el proteccionismo porque:',
    opciones: ['Las industrias maduras necesitan protección frente a la competencia desleal', 'Una industria nueva puede necesitar protección temporal hasta alcanzar escala y competitividad suficientes', 'Los países ricos deben proteger sus mercados para mantener el empleo', 'El libre comercio solo beneficia a los países exportadores de materias primas'],
    correcta: 1,
    explicacion: 'El argumento de la industria naciente (infant industry) defiende la protección temporal de sectores emergentes que, una vez alcancen economías de escala y aprendizaje, podrán competir internacionalmente sin ayuda.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 3,
    enunciado: 'El déficit por cuenta corriente de un país implica necesariamente que:',
    opciones: ['El país tiene déficit presupuestario', 'El país acumula activos netos frente al exterior', 'El país se endeuda con el exterior o vende activos al extranjero (superávit en cuenta financiera)', 'El tipo de cambio de la moneda subirá automáticamente'],
    correcta: 2,
    explicacion: 'La balanza de pagos siempre suma cero. Un déficit por cuenta corriente implica una entrada neta de financiación exterior (préstamos, inversión extranjera directa, etc.), lo que se refleja como superávit en la cuenta financiera.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 3,
    enunciado: 'En un sistema de tipos de cambio fijos, un país con déficit persistente en la balanza de pagos puede corregirlo mediante:',
    opciones: ['Devaluando su moneda con autorización del banco central', 'Apreciando su moneda para encarecer las importaciones', 'Aumentando el tipo de interés para atraer capital a corto plazo sin alterar el tipo de cambio', 'Reduciendo los aranceles para mejorar la balanza comercial'],
    correcta: 0,
    explicacion: 'En un régimen de tipo de cambio fijo, la devaluación (bajada discrecional del valor oficial de la moneda) es el mecanismo de ajuste externo: abarata exportaciones y encarece importaciones, mejorando la balanza comercial.',
  },
  {
    bloque: 'comercio-internacional',
    nivel: 2,
    enunciado: 'Las cuotas de importación y los aranceles coinciden en que ambos:',
    opciones: ['Generan ingresos directos para el Estado', 'Protegen a los productores nacionales de la competencia exterior', 'Fijan un límite máximo al volumen de bienes importados', 'Son instrumentos de política monetaria'],
    correcta: 1,
    explicacion: 'Tanto aranceles como cuotas protegen a los productores nacionales limitando la competencia importada. Difieren en su mecanismo: el arancel actúa por precio y genera ingresos fiscales; la cuota actúa por volumen y no genera ingresos directos al Estado.',
  },

  // ─── EMPRESA ──────────────────────────────────────────────────────────────

  {
    bloque: 'empresa',
    nivel: 1,
    enunciado: 'La función del empresario schumpeteriano se caracteriza principalmente por:',
    opciones: ['Aportar el capital financiero necesario para la empresa', 'La innovación y la introducción de nuevas combinaciones productivas que rompen el equilibrio', 'Gestionar los recursos humanos del día a día', 'Minimizar costes manteniendo la producción constante'],
    correcta: 1,
    explicacion: 'Para Schumpeter el empresario es el agente del cambio: innova (nuevos productos, procesos, mercados, fuentes de materias primas u organización) generando la «destrucción creativa» que impulsa el crecimiento.',
  },
  {
    bloque: 'empresa',
    nivel: 1,
    enunciado: 'En una Sociedad de Responsabilidad Limitada (SRL), la responsabilidad de los socios es:',
    opciones: ['Ilimitada: responden con todo su patrimonio personal', 'Limitada al capital aportado: no arriesgan su patrimonio personal', 'Proporcional al número de empleados de la empresa', 'Ilimitada solo si hay pérdidas superiores al capital social'],
    correcta: 1,
    explicacion: 'En una SRL (o SL) la responsabilidad de los socios queda limitada al capital que han aportado. Su patrimonio personal no responde de las deudas sociales, a diferencia de los autónomos o las sociedades colectivas.',
  },
  {
    bloque: 'empresa',
    nivel: 1,
    enunciado: '¿Cuál es el capital social mínimo legal para constituir una Sociedad Anónima (SA) en España?',
    opciones: ['1 €', '3.000 €', '60.000 €', '1.000 €'],
    correcta: 2,
    explicacion: 'El capital mínimo de una SA en España es de 60.000 €, mientras que una SL puede constituirse desde 1 € tras la Ley 18/2022 «Crea y Crece» (antes el mínimo era 3.000 €). La SA está pensada para empresas de mayor tamaño con capital abierto al público.',
  },
  {
    bloque: 'empresa',
    nivel: 2,
    enunciado: 'El crecimiento externo de la empresa se produce cuando:',
    opciones: ['La empresa amplía su capacidad instalando una nueva fábrica propia', 'La empresa crece reinvirtiendo sus propios beneficios', 'La empresa fusiona, absorbe o adquiere participaciones en otras empresas ya existentes', 'La empresa contrata más trabajadores para su plantilla actual'],
    correcta: 2,
    explicacion: 'El crecimiento externo se basa en la combinación con empresas existentes (fusión, adquisición, participación). El crecimiento interno implica expandir la propia capacidad sin comprar empresas ajenas.',
  },
  {
    bloque: 'empresa',
    nivel: 2,
    enunciado: 'La integración vertical de una empresa supone:',
    opciones: ['Diversificarse hacia sectores sin relación con su actividad principal', 'Unirse a competidores del mismo sector para ganar cuota de mercado', 'Controlar etapas anteriores (integración hacia atrás) o posteriores (hacia delante) de su cadena de valor', 'Establecer filiales en otros países para internacionalizarse'],
    correcta: 2,
    explicacion: 'La integración vertical consiste en que la empresa incorpora fases adicionales de su cadena de valor: hacia atrás (proveedores/materias primas) o hacia delante (distribución/venta al cliente final).',
  },
  {
    bloque: 'empresa',
    nivel: 1,
    enunciado: 'Las 4 P del marketing-mix son:',
    opciones: ['Producto, precio, plaza (distribución) y publicidad', 'Producto, precio, plaza (distribución) y promoción', 'Precio, publicidad, punto de venta y posicionamiento', 'Producción, precio, plaza y personal'],
    correcta: 1,
    explicacion: 'El marketing-mix clásico (McCarthy) comprende: Producto (características, marca), Precio (estrategia de precios), Plaza o distribución (canales) y Promoción (comunicación, publicidad, relaciones públicas).',
  },
  {
    bloque: 'empresa',
    nivel: 2,
    enunciado: 'Una cooperativa se diferencia de una SA en que:',
    opciones: ['La cooperativa tiene capital mínimo de 60.000 €', 'En la cooperativa cada socio tiene un voto independientemente del capital aportado', 'La cooperativa solo puede operar en el sector agrícola', 'En la cooperativa los socios responden ilimitadamente de las deudas'],
    correcta: 1,
    explicacion: 'El principio democrático de las cooperativas establece que cada socio-trabajador o socio-usuario tiene un voto, independientemente del capital aportado, a diferencia de las SA donde los votos son proporcionales a las acciones.',
  },
  {
    bloque: 'empresa',
    nivel: 2,
    enunciado: 'El área de producción de una empresa se ocupa de:',
    opciones: ['Captar clientes y gestionar las ventas', 'Transformar factores productivos en bienes o servicios finales eficientemente', 'Gestionar la nómina y la formación del personal', 'Elaborar los estados financieros anuales'],
    correcta: 1,
    explicacion: 'El área de producción (u operaciones) gestiona el proceso de transformación de inputs (materias primas, trabajo, energía) en outputs (productos o servicios) optimizando calidad, coste y tiempo.',
  },
  {
    bloque: 'empresa',
    nivel: 3,
    enunciado: 'Una empresa española fabricante de calzado adquiere una fábrica de cuero (proveedor). Esto es un ejemplo de:',
    opciones: ['Integración horizontal', 'Diversificación no relacionada', 'Integración vertical hacia atrás', 'Integración vertical hacia delante'],
    correcta: 2,
    explicacion: 'Al adquirir a un proveedor (fase anterior en la cadena de valor), la empresa se integra verticalmente hacia atrás (upstream), controlando la fabricación de su principal input.',
  },
  {
    bloque: 'empresa',
    nivel: 3,
    enunciado: 'Una empresa con una estrategia de «liderazgo en costes» (Porter) busca principalmente:',
    opciones: ['Ofrecer un producto único que los clientes perciban como diferente y estén dispuestos a pagar más', 'Ser el productor con costes totales más bajos del sector para obtener mayor margen o ganar cuota con precios bajos', 'Concentrarse en un segmento de mercado muy específico con alta disposición a pagar', 'Crecer externamente adquiriendo competidores para ganar poder de mercado'],
    correcta: 1,
    explicacion: 'La estrategia de liderazgo en costes de Porter consiste en producir a menor coste que todos los rivales del sector, bien para obtener mayor margen al precio de mercado o para atraer clientes sensibles al precio.',
  },
  {
    bloque: 'empresa',
    nivel: 1,
    enunciado: 'Un trabajador autónomo responde de las deudas de su negocio con:',
    opciones: ['Solo el capital invertido en el negocio', 'Todo su patrimonio personal presente y futuro (responsabilidad ilimitada)', 'El importe máximo del Fondo de Garantía Salarial', 'Hasta el doble del capital invertido'],
    correcta: 1,
    explicacion: 'El autónomo no tiene separación jurídica entre su patrimonio personal y el empresarial: responde de las deudas del negocio con todos sus bienes presentes y futuros, lo que supone una responsabilidad ilimitada.',
  },

  // ─── FALLOS DE MERCADO ────────────────────────────────────────────────────

  {
    bloque: 'fallos-mercado',
    nivel: 1,
    enunciado: 'Una externalidad negativa se produce cuando:',
    opciones: ['El precio de mercado es inferior al coste de producción', 'Una actividad económica impone costes a terceros que no son compensados a través del mercado', 'Una empresa obtiene beneficios extraordinarios sin competencia', 'El consumidor paga más de lo que valora el bien'],
    correcta: 1,
    explicacion: 'Las externalidades negativas son costes externos: la actividad de un agente perjudica a otros que no participan en la transacción y no reciben compensación (p. ej., contaminación industrial).',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 1,
    enunciado: 'El coste social de producir un bien con externalidades negativas es:',
    opciones: ['Igual al coste privado de las empresas', 'Menor que el coste privado porque los terceros absorben parte del coste', 'Mayor que el coste privado porque incluye los costes externos impuestos a terceros', 'El precio que fija el gobierno para ese bien'],
    correcta: 2,
    explicacion: 'Coste social = coste privado + coste externo. Con externalidades negativas, la sociedad soporta más costes que los que la empresa registra, por lo que el mercado libre sobreproducirá ese bien.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 2,
    enunciado: 'Un impuesto pigouviano busca corregir una externalidad negativa al:',
    opciones: ['Subvencionar a las empresas contaminantes para que inviertan en tecnología limpia', 'Gravar la actividad que genera la externalidad de modo que el coste privado iguale al coste social', 'Fijar un precio máximo al bien afectado por la contaminación', 'Prohibir por ley la actividad contaminante sin compensación'],
    correcta: 1,
    explicacion: 'El impuesto pigouviano (propuesto por Pigou) grava la actividad contaminante por un importe igual al coste externo, internalizando la externalidad: el precio de mercado sube hasta reflejar el verdadero coste social.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 1,
    enunciado: 'Las dos características que definen a un bien público son:',
    opciones: ['Exclusión y rivalidad en el consumo', 'No exclusión y no rivalidad en el consumo', 'Exclusión y no rivalidad', 'No exclusión y rivalidad'],
    correcta: 1,
    explicacion: 'Un bien público puro es no excluible (no se puede impedir su consumo a quien no paga) y no rival (el consumo de una persona no reduce la disponibilidad para otras), como la defensa nacional o el alumbrado público.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 2,
    enunciado: 'El problema del «polizón» (free-rider) en los bienes públicos consiste en que:',
    opciones: ['Los productores ofrecen el bien por debajo del coste para expulsar a la competencia', 'Los consumidores ocultarán su verdadera valoración del bien para no pagar y beneficiarse igualmente', 'El Estado puede excluir fácilmente a quienes no pagan impuestos', 'Los bienes públicos generan siempre externalidades positivas'],
    correcta: 1,
    explicacion: 'Como nadie puede ser excluido de disfrutar un bien público, los consumidores tienen incentivos a no pagar (comportarse como polizones), por lo que el mercado privado suministra insuficiente cantidad de estos bienes.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 2,
    enunciado: 'La selección adversa (adverse selection) es un problema de información asimétrica que se produce:',
    opciones: ['Después de firmar un contrato, cuando una parte actúa de forma oportunista', 'Antes de firmar el contrato: la parte mejor informada es seleccionada por la peor parte en condiciones desfavorables para esta', 'Cuando el Estado prohíbe la venta de bienes defectuosos sin etiquetar', 'Cuando el monopolista discrimina precios entre diferentes consumidores'],
    correcta: 1,
    explicacion: 'La selección adversa ocurre antes de la transacción: por ejemplo, en seguros de salud los enfermos crónicos (mejor informados sobre su riesgo) se aseguran más que los sanos, elevando los costes para la aseguradora.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 2,
    enunciado: 'El riesgo moral (moral hazard) aparece cuando:',
    opciones: ['Una parte tiene información privada antes de firmar el contrato', 'Una vez cubierto por un seguro u otro contrato, un agente cambia su comportamiento asumiendo más riesgos', 'El vendedor de un bien usado oculta información sobre su calidad', 'El Estado provee de bienes públicos sin cobrar impuestos'],
    correcta: 1,
    explicacion: 'El riesgo moral surge tras la firma del contrato: el asegurado o el beneficiario de una garantía tiene incentivos para adoptar conductas más arriesgadas porque no soporta íntegramente las consecuencias negativas.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 1,
    enunciado: 'El mercado de coches usados de Akerlof ilustra:',
    opciones: ['La externalidad negativa de la contaminación del tráfico', 'El problema de selección adversa cuando el vendedor conoce la calidad del coche pero el comprador no', 'El riesgo moral de los concesionarios de coches nuevos', 'Un bien público impuro de consumo rival'],
    correcta: 1,
    explicacion: 'En el modelo de Akerlof, los vendedores saben si su coche es un «limón» (defectuoso) o no, pero los compradores no pueden distinguirlos antes de la compra. El precio medio refleja calidad media, expulsando a los coches buenos del mercado.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 3,
    enunciado: 'Con una externalidad negativa, el mercado libre produce:',
    opciones: ['Menos cantidad de la socialmente óptima, porque el precio es demasiado alto', 'La cantidad socialmente óptima, porque el mercado se autorregula', 'Más cantidad de la socialmente óptima, porque el precio de mercado es menor que el coste social', 'Más cantidad de la socialmente óptima, porque el coste privado supera al social'],
    correcta: 2,
    explicacion: 'Con externalidad negativa, el coste privado < coste social, por lo que el precio de mercado es «demasiado barato»: se produce en exceso respecto al óptimo social (donde CMg social = beneficio marginal social).',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 3,
    enunciado: 'Una externalidad positiva (p. ej., vacunarse contra la gripe) implica que el mercado produce:',
    opciones: ['La cantidad óptima, porque el beneficio privado refleja el beneficio social', 'Demasiado, porque los individuos sobrevaloran el beneficio para terceros', 'Menos de lo socialmente óptimo, porque el beneficio social es mayor que el beneficio privado', 'Demasiado, porque el coste privado es mayor que el coste social'],
    correcta: 2,
    explicacion: 'Con externalidad positiva el beneficio social supera al privado: los agentes deciden basándose solo en su beneficio individual, sin considerar el beneficio externo para terceros, resultando en infraproducción respecto al óptimo social.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 2,
    enunciado: '¿Cuál de las siguientes es una medida de regulación para corregir el poder de monopolio?',
    opciones: ['Subvencionar al monopolista para reducir su precio', 'Fijar un precio máximo igual al coste marginal (regulación al coste marginal)', 'Eliminar todos los impuestos que pague el monopolista', 'Aumentar las barreras de entrada para proteger al monopolista'],
    correcta: 1,
    explicacion: 'Regulando el precio máximo al nivel del coste marginal (P = CMg), el regulador obliga al monopolista a comportarse como si hubiera competencia, eliminando el peso muerto, aunque puede generar pérdidas si hay costes fijos elevados.',
  },
  {
    bloque: 'fallos-mercado',
    nivel: 3,
    enunciado: 'En el teorema de Coase, si los derechos de propiedad están bien definidos y los costes de transacción son nulos:',
    opciones: ['El Estado debe intervenir siempre para corregir las externalidades', 'Las partes pueden negociar privadamente y alcanzar el resultado eficiente, independientemente de quién tenga el derecho', 'La externalidad no existe porque el mercado la elimina automáticamente', 'La asignación eficiente solo se alcanza si el contaminador paga'],
    correcta: 1,
    explicacion: 'El teorema de Coase establece que si los derechos de propiedad están definidos y la negociación es costeable, las partes afectadas por una externalidad llegarán por sí solas al resultado eficiente, independientemente de a quién se asignen inicialmente los derechos.',
  },

  // ─── CONTABILIDAD (Balance, resultados, FM, ratios) ──────────────────────

  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'En el balance de situación de una empresa se debe cumplir que:',
    opciones: ['Activo = Patrimonio neto + Pasivo', 'Activo + Patrimonio neto = Pasivo', 'Patrimonio neto = Activo + Pasivo', 'Activo = Pasivo solamente'],
    correcta: 0,
    explicacion: 'La ecuación fundamental del patrimonio establece que Activo = Patrimonio neto + Pasivo. El activo (bienes y derechos) se financia con recursos propios (PN) y ajenos (Pasivo).',
  },
  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'Cuando el fondo de maniobra es negativo significa que:',
    opciones: ['El activo corriente supera al pasivo corriente', 'Parte del activo no corriente está financiada con pasivo corriente (deudas a corto plazo)', 'La empresa tiene quiebra técnica con seguridad', 'El activo corriente está financiado con recursos a largo plazo'],
    correcta: 1,
    explicacion: 'FM = AC − PC < 0 implica que PC > AC; es decir, deudas a corto plazo superan a los activos líquidos, por lo que parte del inmovilizado se financia con deuda a corto: situación financiera delicada.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'Si el activo corriente de una empresa es igual a su pasivo corriente, el fondo de maniobra es:',
    opciones: ['Positivo', 'Negativo', 'Cero', 'Indeterminado'],
    correcta: 2,
    explicacion: 'Fondo de maniobra = Activo corriente − Pasivo corriente = 0. Los activos líquidos cubren exactamente las deudas a corto plazo; la situación es equilibrada aunque sin margen de seguridad.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'Si el ratio de liquidez (activo corriente / pasivo corriente) de una empresa vale 0,74, el fondo de maniobra será:',
    opciones: ['Positivo', 'Negativo', 'Cero', 'No se puede determinar'],
    correcta: 1,
    explicacion: 'Un ratio de liquidez < 1 indica que el activo corriente es menor que el pasivo corriente, por lo que FM = AC − PC < 0 (fondo de maniobra negativo).',
  },
  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'La amortización es:',
    opciones: ['Las pérdidas anuales de la empresa', 'La pérdida de valor del activo no corriente por uso, tiempo u obsolescencia', 'Una deuda con el banco', 'El beneficio no distribuido entre los socios'],
    correcta: 1,
    explicacion: 'La amortización refleja la depreciación sistemática de los activos fijos (maquinaria, instalaciones, vehículos). No es una salida de dinero sino un gasto contable que reduce el valor del activo.',
  },
  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'Los beneficios no distribuidos por la empresa se contabilizan como:',
    opciones: ['Resultado del ejercicio en el pasivo', 'Reservas en el patrimonio neto', 'Proveedores en el pasivo corriente', 'Inmovilizado intangible en el activo'],
    correcta: 1,
    explicacion: 'Los beneficios retenidos (no distribuidos como dividendos) pasan a reservas, que forman parte del patrimonio neto y refuerzan la autofinanciación de la empresa.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'Una deuda con una entidad financiera a devolver en 18 meses se clasifica como:',
    opciones: ['Pasivo no corriente (largo plazo)', 'Activo no corriente', 'Pasivo corriente (corto plazo)', 'Patrimonio neto'],
    correcta: 0,
    explicacion: 'El pasivo no corriente agrupa las deudas con vencimiento superior a un año (12 meses). 18 meses > 12 meses, por lo que esta deuda se registra como pasivo no corriente.',
  },
  {
    bloque: 'contabilidad',
    nivel: 1,
    enunciado: 'El resultado de explotación en la cuenta de pérdidas y ganancias representa:',
    opciones: ['El resultado de operaciones financieras', 'El beneficio o pérdida procedente de la actividad principal de la empresa', 'Los ingresos extraordinarios', 'El impuesto de sociedades pagado'],
    correcta: 1,
    explicacion: 'El resultado de explotación (EBIT) recoge los ingresos y gastos de la actividad ordinaria de la empresa, antes de intereses e impuestos. Es el indicador de la rentabilidad operativa.',
  },
  {
    bloque: 'contabilidad',
    nivel: 3,
    enunciado: 'Cuando el ratio de garantía (activo total / exigible total) es igual a la unidad, significa que la empresa:',
    opciones: ['Tiene beneficios elevados', 'Los fondos propios son mayores que las deudas', 'No tiene patrimonio neto (fondos propios = 0, posible quiebra técnica)', 'Tiene el máximo nivel de solvencia'],
    correcta: 2,
    explicacion: 'Activo total = Pasivo total → PN = Activo − Pasivo = 0. La empresa carece de recursos propios (está completamente endeudada), lo que se conoce como quiebra técnica o situación de desbalance.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'Dos empresas tienen la misma cifra de negocio (ventas). ¿Qué podemos afirmar sobre su rentabilidad?',
    opciones: ['Necesariamente tienen la misma rentabilidad económica', 'Necesariamente tienen la misma rentabilidad financiera', 'No significa que tengan la misma rentabilidad: depende también de sus costes y activos', 'La empresa con menor activo tendrá menor rentabilidad'],
    correcta: 2,
    explicacion: 'La rentabilidad económica (BAIT / Activo total) y financiera (BN / Fondos propios) dependen de márgenes y estructura de capital, no solo de las ventas.',
  },
  {
    bloque: 'contabilidad',
    nivel: 3,
    enunciado: 'Los programas informáticos adquiridos por una empresa se contabilizan en el activo como:',
    opciones: ['Equipos para procesos de información (activo material)', 'Material de oficina (gasto corriente)', 'Aplicaciones informáticas (inmovilizado intangible)', 'Existencias (activo corriente)'],
    correcta: 2,
    explicacion: 'Las licencias de software y aplicaciones informáticas son activos intangibles (no tienen forma física) y se registran dentro del inmovilizado intangible del activo no corriente.',
  },
  {
    bloque: 'contabilidad',
    nivel: 2,
    enunciado: 'El fondo de maniobra de una empresa es:',
    opciones: ['El capital desembolsado más las reservas', 'La parte del activo corriente financiada con recursos financieros a largo plazo', 'El beneficio neto del ejercicio', 'El total del pasivo corriente de la empresa'],
    correcta: 1,
    explicacion: 'El fondo de maniobra (FM = AC − PC) representa la parte del activo circulante que está financiada con recursos permanentes (propios o ajenos a largo plazo), actuando como colchón de seguridad financiera.',
  },
  {
    bloque: 'contabilidad',
    nivel: 3,
    enunciado: 'Una empresa tiene: Activo no corriente 80.000 €, Activo corriente 20.000 €, Pasivo no corriente 40.000 €, Pasivo corriente 30.000 €. ¿Cuál es su fondo de maniobra y su patrimonio neto?',
    opciones: ['FM = −10.000 €; PN = 30.000 €', 'FM = 10.000 €; PN = 50.000 €', 'FM = −10.000 €; PN = 50.000 €', 'FM = 10.000 €; PN = 30.000 €'],
    correcta: 0,
    explicacion: 'FM = AC − PC = 20.000 − 30.000 = −10.000 € (situación de tensión financiera). PN = Activo total − Pasivo total = 100.000 − 70.000 = 30.000 €.',
  },
];

export function preguntasDeBloque(bloque: string): PreguntaBanco[] {
  return BANCO.filter((p) => p.bloque === bloque);
}
