/**
 * Display names of the decision-tree KPIs.
 *
 * The trees key their KPIs by an id («claridad_futuro»), and the KPI bar used to
 * print that id: Castilian, without accents and with underscores, also on the
 * Valencian pages. One name per id serves every tree that uses it (`caja`
 * appears in twenty), so a label is translated once. A tree can still name its
 * own KPIs in `intro.kpi_labels`, which wins over these.
 *
 * `kpi-labels.test.ts` fails when a tree uses an id with no name here or in the
 * tree, so a new tree cannot reach a page with a raw id again.
 */
import type { Locale } from '@/i18n/locale';

/** Ids shared by the Castilian and the Valencian edition of a tree: [es, ca]. */
const NOMBRES: Record<string, readonly [es: string, ca: string]> = {
  // Cultura Jurídica i Democràtica
  seguridad_juridica: ['Seguridad jurídica', 'Seguretat jurídica'],
  riesgo_de_sancion: ['Riesgo de sanción', 'Risc de sanció'],
  credibilidad_ante_el_ayuntamiento: ['Credibilidad ante el ayuntamiento', "Credibilitat davant l'ajuntament"],
  compensacion_obtenida: ['Compensación obtenida', 'Compensació obtinguda'],
  coste_de_bolsillo: ['Coste de bolsillo', 'Cost de butxaca'],
  solidez_de_la_prueba: ['Solidez de la prueba', 'Solidesa de la prova'],
  rigor_del_argumento: ['Rigor del argumento', "Rigor de l'argument"],
  apoyo_del_alumnado: ['Apoyo del alumnado', "Suport de l'alumnat"],
  credibilidad_ante_el_claustro: ['Credibilidad ante el claustro', 'Credibilitat davant el claustre'],
  patrimonio_neto: ['Patrimonio neto', 'Patrimoni net'],
  riesgo_personal: ['Riesgo personal', 'Risc personal'],
  tiempo_disponible: ['Tiempo disponible', 'Temps disponible'],
  dinero_cobrado: ['Dinero cobrado', 'Diners cobrats'],
  derechos_acreditados: ['Derechos acreditados', 'Drets acreditats'],
  relacion_con_la_empresa: ['Relación con la empresa', "Relació amb l'empresa"],
  neto_esperado: ['Neto esperado', 'Net esperat'],
  cobertura_y_derechos: ['Cobertura y derechos', 'Cobertura i drets'],
  dano_a_la_persona: ['Daño a la persona', 'Dany a la persona'],
  riesgo_juridico_propio: ['Riesgo jurídico propio', 'Risc jurídic propi'],
  confianza_del_grupo: ['Confianza del grupo', 'Confiança del grup'],
  dinero_recuperado: ['Dinero recuperado', 'Diners recuperats'],
  coste_del_proceso: ['Coste del proceso', 'Cost del procés'],
  tiempo_invertido: ['Tiempo invertido', 'Temps invertit'],
  financiacion: ['Financiación', 'Finançament'],
  margen_de_decision: ['Margen de decisión', 'Marge de decisió'],
  apoyo_interno: ['Apoyo interno', 'Suport intern'],
  patrimonio_a_salvo: ['Patrimonio a salvo', 'Patrimoni fora de perill'],
  caja: ['Caja', 'Caixa'],
  credibilidad: ['Credibilidad', 'Credibilitat'],
  riesgo_fiscal: ['Riesgo fiscal', 'Risc fiscal'],
  respaldo_documental: ['Respaldo documental', 'Suport documental'],
  beneficio: ['Beneficio', 'Benefici'],
  riesgo_sancionador: ['Riesgo sancionador', 'Risc sancionador'],
  reputacion: ['Reputación', 'Reputació'],
  mejora_mensual: ['Mejora mensual', 'Millora mensual'],
  respaldo_plantilla: ['Respaldo de la plantilla', 'Suport de la plantilla'],
  paz_social: ['Paz social', 'Pau social'],

  // Economía 1.º BACH
  presupuesto: ['Presupuesto', 'Pressupost'],
  satisfaccion_vecinos: ['Satisfacción vecinal', 'Satisfacció veïnal'],
  empleo_local: ['Empleo local', 'Ocupació local'],
  motivacion: ['Motivación', 'Motivació'],
  coste_oportunidad_acumulado: ['Coste de oportunidad acumulado', "Cost d'oportunitat acumulat"],
  claridad_futuro: ['Claridad sobre el futuro', 'Claredat sobre el futur'],
  ahorro_mensual: ['Ahorro mensual', 'Estalvi mensual'],
  fondo_emergencia: ['Fondo de emergencia', "Fons d'emergència"],
  inversion_futura: ['Inversión futura', 'Inversió futura'],
  ingreso_mensual: ['Ingreso mensual', 'Ingrés mensual'],
  ocupacion_pct: ['Ocupación (%)', 'Ocupació (%)'],
  estabilidad: ['Estabilidad', 'Estabilitat'],
  precio_litro_cts: ['Precio del litro (cént.)', 'Preu del litre (cèntims)'],
  litros_mes: ['Litros al mes', 'Litres al mes'],
  margen_bruto_cts: ['Margen bruto (cént.)', 'Marge brut (cèntims)'],
  mw_instalados: ['MW instalados', 'MW instal·lats'],
  ingreso_apicultor: ['Ingresos del apicultor', "Ingressos de l'apicultor"],
  impacto_ambiental: ['Impacto ambiental', 'Impacte ambiental'],
  pib_real_crecimiento_pct: ['Crecimiento del PIB real', 'Creixement del PIB real'],
  confianza_diagnostico: ['Confianza en el diagnóstico', 'Confiança en el diagnòstic'],
  precision_analisis: ['Precisión del análisis', "Precisió de l'anàlisi"],
  facturacion_pct: ['Facturación (%)', 'Facturació (%)'],
  empleo: ['Empleo', 'Ocupació'],
  liquidez_meses: ['Liquidez (meses)', 'Liquiditat (mesos)'],
  salario_oferta: ['Salario ofrecido', 'Salari oferit'],
  satisfaccion_oferta: ['Satisfacción con la oferta', "Satisfacció amb l'oferta"],
  posicion_negociacion: ['Posición negociadora', 'Posició negociadora'],
  ahorro_adrián: ['Ahorro de Adrián', "Estalvi d'Adrián"],
  riesgo_cartera: ['Riesgo de la cartera', 'Risc de la cartera'],
  comprension_sistema: ['Comprensión del sistema', 'Comprensió del sistema'],
  pib_crecimiento_pct: ['Crecimiento del PIB', 'Creixement del PIB'],
  paro_pct: ['Paro', 'Atur'],
  deficit_pct_pib: ['Déficit público', 'Dèficit públic'],
  facturacion_ke: ['Facturación (k€)', 'Facturació (k€)'],
  empleos: ['Empleos', 'Llocs de treball'],
  exposicion_riesgo: ['Exposición al riesgo', 'Exposició al risc'],

  // Economía 4.º ESO
  capital: ['Capital', 'Capital'],
  dias_feria: ['Días de feria', 'Dies de fira'],
  ventas_estimadas: ['Ventas estimadas', 'Vendes estimades'],
  vistas: ['Visualizaciones', 'Visualitzacions'],
  suscriptores: ['Suscriptores', 'Subscriptors'],
  horas_disponibles_semana: ['Horas libres a la semana', 'Hores lliures a la setmana'],
  stock_prendas: ['Prendas en stock', 'Peces en estoc'],
  capital_invertido: ['Capital invertido', 'Capital invertit'],
  seguidores: ['Seguidores', 'Seguidors'],
  usuarios_potenciales: ['Usuarios potenciales', 'Usuaris potencials'],
  validaciones_reales: ['Validaciones reales', 'Validacions reals'],
  tiempo_investigacion_horas: ['Investigación (horas)', 'Investigació (hores)'],
  dias_para_decidir: ['Días para decidir', 'Dies per a decidir'],
  riesgo_estimado: ['Riesgo estimado', 'Risc estimat'],
  dias_para_entrega: ['Días para la entrega', "Dies per a l'entrega"],
  porcentaje_completado: ['Completado (%)', 'Completat (%)'],
  cohesion_equipo: ['Cohesión del equipo', "Cohesió de l'equip"],
  paga_mensual: ['Paga mensual', 'Paga mensual'],
  ahorro_actual: ['Ahorro actual', 'Estalvi actual'],
  objetivo_3_meses: ['Objetivo a 3 meses', 'Objectiu a 3 mesos'],
  salario_bruto_mes: ['Salario bruto al mes', 'Salari brut al mes'],
  horas_semana: ['Horas a la semana', 'Hores a la setmana'],
  duracion_meses: ['Duración (meses)', 'Durada (mesos)'],
  casillas_bmc_rellenas: ['Casillas del BMC rellenas', 'Caselles del BMC emplenades'],
  usuarios_testados: ['Usuarios que lo han probado', "Usuaris que l'han provat"],
  dias_para_feria: ['Días para la feria', 'Dies per a la fira'],
  usuarios_validados: ['Usuarios validados', 'Usuaris validats'],
  claridad_pitch: ['Claridad del pitch', 'Claredat del pitch'],
  segundos_disponibles: ['Segundos disponibles', 'Segons disponibles'],

  // Empresa y Diseño de Modelos de Negocio
  clientes: ['Clientes', 'Clients'],
  clientes_mes: ['Clientes al mes', 'Clients al mes'],
  satisfaccion: ['Satisfacción', 'Satisfacció'],

  // Economía, Emprendimiento y Actividad Empresarial
  partidas_demandadas: ['Partidas demandadas', 'Partides demanades'],
  satisfaccion_general: ['Satisfacción general', 'Satisfacció general'],
  descargas: ['Descargas', 'Descàrregues'],
  apuntes_subidos: ['Apuntes subidos', 'Apunts pujats'],
  dinero_restante: ['Dinero restante', 'Diners restants'],
  clientes_fijos: ['Clientes fijos', 'Clients fixos'],
  reputacion_sostenible: ['Reputación sostenible', 'Reputació sostenible'],
  dinero: ['Dinero', 'Diners'],
  conocimiento_financiero: ['Conocimiento financiero', 'Coneixement financer'],
  riesgo_asumido: ['Riesgo asumido', 'Risc assumit'],
  coesion_equipo: ['Cohesión del equipo', "Cohesió de l'equip"],
  calidad_presentacion: ['Calidad de la presentación', 'Qualitat de la presentació'],
  bienestar_laura: ['Bienestar de Laura', 'Benestar de Laura'],
  validacion_real: ['Validación real', 'Validació real'],
  entusiasmo_personal: ['Entusiasmo personal', 'Entusiasme personal'],
  dinero_disponible: ['Dinero disponible', 'Diners disponibles'],
  claridad_proposito: ['Claridad del propósito', 'Claredat del propòsit'],
  impacto_ods: ['Impacto en los ODS', 'Impacte en els ODS'],
  pedidos_mensual: ['Pedidos al mes', 'Comandes al mes'],
  capacidad_actual: ['Capacidad actual', 'Capacitat actual'],
  cultura_empresa: ['Cultura de empresa', "Cultura d'empresa"],
  alumnos: ['Alumnos', 'Alumnes'],
  precio_hora: ['Precio por hora', 'Preu per hora'],
  reputacion_calidad: ['Reputación de calidad', 'Reputació de qualitat'],
  eficiencia_operativa: ['Eficiencia operativa', 'Eficiència operativa'],
  satisfaccion_equipo: ['Satisfacción del equipo', "Satisfacció de l'equip"],
  ventas_online: ['Ventas en línea', 'Vendes en línia'],

  // Formación y Orientación Personal y Profesional
  confianza: ['Confianza', 'Confiança'],
  claridad_identidad: ['Claridad de identidad', "Claredat d'identitat"],
  autonomia: ['Autonomía', 'Autonomia'],
  salud_mental: ['Salud mental', 'Salut mental'],
  rendimiento: ['Rendimiento', 'Rendiment'],
  red_apoyo: ['Red de apoyo', 'Xarxa de suport'],
  autonomia_digital: ['Autonomía digital', 'Autonomia digital'],
  bienestar: ['Bienestar', 'Benestar'],

  // Gestión de Proyectos de Emprendimiento
  pedidos_mes: ['Pedidos al mes', 'Comandes al mes'],
  validacion_clientes: ['Validación con clientes', 'Validació amb clients'],
  claridad_oportunidad: ['Claridad de la oportunidad', "Claredat de l'oportunitat"],
  usuarios: ['Usuarios', 'Usuaris'],
  ingresos_mes: ['Ingresos al mes', 'Ingressos al mes'],
  tarros_stock: ['Tarros en stock', 'Pots en estoc'],
  costes_mes: ['Costes al mes', 'Costos al mes'],
  lista_espera_dias: ['Lista de espera (días)', "Llista d'espera (dies)"],
  ventas_semana: ['Ventas a la semana', 'Vendes a la setmana'],
  deudas_pendientes: ['Deudas pendientes', 'Deutes pendents'],
  retorno_local_pct: ['Retorno local (%)', 'Retorn local (%)'],
  huella_estimada_kg_co2: ['Huella estimada (kg CO₂)', 'Petjada estimada (kg CO₂)'],

  // Itinerario Personal para la Empleabilidad I
  empleabilidad_interna: ['Empleabilidad interna', 'Ocupabilitat interna'],
  empleabilidad_externa: ['Empleabilidad externa', 'Ocupabilitat externa'],
  red_contactos: ['Red de contactos', 'Xarxa de contactes'],
  autoconocimiento: ['Autoconocimiento', 'Autoconeixement'],
  adecuacion_perfil: ['Adecuación del perfil', 'Adequació del perfil'],
  claridad_objetivo: ['Claridad del objetivo', "Claredat de l'objectiu"],
  plan_accion: ['Plan de acción', "Pla d'acció"],
  margen_tiempo: ['Margen de tiempo (días)', 'Marge de temps (dies)'],
  integracion_equipo: ['Integración en el equipo', "Integració en l'equip"],
  aprendizaje_real: ['Aprendizaje real', 'Aprenentatge real'],
  perfil_empleable: ['Perfil empleable', 'Perfil ocupable'],
  presencia_digital: ['Presencia digital', 'Presència digital'],
  coherencia_perfil: ['Coherencia del perfil', 'Coherència del perfil'],
  reputacion_online: ['Reputación en línea', 'Reputació en línia'],
  conocimiento_derechos: ['Conocimiento de los derechos', 'Coneixement dels drets'],
  poder_negociacion: ['Poder de negociación', 'Poder de negociació'],
  proteccion_laboral: ['Protección laboral', 'Protecció laboral'],
  conocimiento_ss: ['Conocimiento de la Seguridad Social', 'Coneixement de la Seguretat Social'],
  proteccion_prestaciones: ['Protección de las prestaciones', 'Protecció de les prestacions'],
  capacidad_reclamacion: ['Capacidad de reclamar', 'Capacitat de reclamar'],
  seguridad_escena: ['Seguridad de la escena', "Seguretat de l'escena"],
  atencion_accidentado: ['Atención al accidentado', "Atenció a l'accidentat"],
  gestion_emergencia: ['Gestión de la emergencia', "Gestió de l'emergència"],
  bienestar_laboral: ['Bienestar laboral', 'Benestar laboral'],
  gestion_estres: ['Gestión del estrés', "Gestió de l'estrés"],
  conocimiento_recursos: ['Conocimiento de recursos', 'Coneixement de recursos'],

  // Itinerario Personal para la Empleabilidad II
  candidaturas_activas: ['Candidaturas activas', 'Candidatures actives'],
  entrevistas_conseguidas: ['Entrevistas conseguidas', 'Entrevistes aconseguides'],
  red_profesional: ['Red profesional', 'Xarxa professional'],
  reputacion_digital: ['Reputación digital', 'Reputació digital'],
  confianza_reclutador: ['Confianza del reclutador', 'Confiança del reclutador'],
  avance_proyecto: ['Avance del proyecto', 'Avanç del projecte'],
  riesgo_entrega: ['Riesgo en la entrega', "Risc en l'entrega"],
  seguridad_economica: ['Seguridad económica', 'Seguretat econòmica'],
  aprendizaje_emprendedor: ['Aprendizaje emprendedor', 'Aprenentatge emprenedor'],
  confianza_hipotesis: ['Confianza en la hipótesis', 'Confiança en la hipòtesi'],
  capital_inicial: ['Capital inicial', 'Capital inicial'],
  capacidad_comercial: ['Capacidad comercial', 'Capacitat comercial'],
  riesgo_societario: ['Riesgo societario', 'Risc societari'],
  servicios_vendidos: ['Servicios vendidos', 'Serveis venuts'],
  tasa_conversion: ['Conversión (%)', 'Conversió (%)'],
  punto_muerto_distancia: ['Distancia al punto muerto', 'Distància al punt mort'],
  viabilidad_financiera: ['Viabilidad financiera', 'Viabilitat financera'],
  impacto_social: ['Impacto social', 'Impacte social'],
  riesgo_arranque: ['Riesgo de arranque', "Risc d'arrancada"],
  clientes_captados: ['Clientes captados', 'Clients captats'],
  viabilidad_calculada: ['Viabilidad calculada', 'Viabilitat calculada'],
  colchon_tesoreria: ['Colchón de tesorería', 'Coixí de tresoreria'],

  // Taller de Economía 3.º ESO
  objetivos_cumplidos: ['Objetivos cumplidos', 'Objectius complits'],
  compras_lista: ['Compras de la lista', 'Compres de la llista'],
  relacion_vendedor: ['Relación con el vendedor', 'Relació amb el venedor'],
  ahorro: ['Ahorro', 'Estalvi'],
  calidad_movil: ['Calidad del móvil', 'Qualitat del mòbil'],
  decision_inteligente: ['Decisión inteligente', 'Decisió intel·ligent'],
  saldo: ['Saldo', 'Saldo'],
  seguridad_digital: ['Seguridad digital', 'Seguretat digital'],
  control_gastos: ['Control de gastos', 'Control de despeses'],
  ahorro_acumulado: ['Ahorro acumulado', 'Estalvi acumulat'],
  objetivo: ['Objetivo', 'Objectiu'],
  meses_restantes: ['Meses restantes', 'Mesos restants'],
  pulseras_vendidas: ['Pulseras vendidas', 'Polseres venudes'],
  aprendizaje: ['Aprendizaje', 'Aprenentatge'],
  derechos_protegidos: ['Derechos protegidos', 'Drets protegits'],
  experiencia: ['Experiencia', 'Experiència'],
  iva_pagado: ['IVA pagado', 'IVA pagat'],
  comprension_fiscal: ['Comprensión fiscal', 'Comprensió fiscal'],
  prendas_reutilizadas: ['Prendas reutilizadas', 'Peces reutilitzades'],
  participacion: ['Participación', 'Participació'],
};

/** Ids that only the Valencian edition of a tree uses (the CJD trees key theirs in Valencian). */
const NOMBRES_SOLO_CA: Record<string, string> = {
  benefici: 'Benefici',
  caixa: 'Caixa',
  cobertura_i_drets: 'Cobertura i drets',
  compensacio_obtinguda: 'Compensació obtinguda',
  confianca_del_grup: 'Confiança del grup',
  cost_de_butxaca: 'Cost de butxaca',
  cost_del_proces: 'Cost del procés',
  credibilitat: 'Credibilitat',
  credibilitat_davant_el_claustre: 'Credibilitat davant el claustre',
  credibilitat_davant_l_ajuntament: "Credibilitat davant l'ajuntament",
  dany_a_la_persona: 'Dany a la persona',
  diners_cobrats: 'Diners cobrats',
  diners_recuperats: 'Diners recuperats',
  drets_acreditats: 'Drets acreditats',
  financament: 'Finançament',
  marge_de_decisio: 'Marge de decisió',
  millora_mensual: 'Millora mensual',
  net_esperat: 'Net esperat',
  patrimoni_fora_de_perill: 'Patrimoni fora de perill',
  patrimoni_net: 'Patrimoni net',
  pau_social: 'Pau social',
  relacio_amb_l_empresa: "Relació amb l'empresa",
  reputacio: 'Reputació',
  rigor_de_l_argument: "Rigor de l'argument",
  risc_de_sancio: 'Risc de sanció',
  risc_fiscal: 'Risc fiscal',
  risc_juridic_propi: 'Risc jurídic propi',
  risc_personal: 'Risc personal',
  risc_sancionador: 'Risc sancionador',
  seguretat_juridica: 'Seguretat jurídica',
  solidesa_de_la_prova: 'Solidesa de la prova',
  suport_de_l_alumnat: "Suport de l'alumnat",
  suport_documental: 'Suport documental',
  suport_intern: 'Suport intern',
  suport_plantilla: 'Suport de la plantilla',
  temps_disponible: 'Temps disponible',
  temps_invertit: 'Temps invertit',
};

/** The shared name of a KPI id in `locale`, or undefined when there is none. */
export function nombreKpi(id: string, locale: Locale): string | undefined {
  const par = NOMBRES[id];
  if (par) return locale === 'ca' ? par[1] : par[0];
  return locale === 'ca' ? NOMBRES_SOLO_CA[id] : undefined;
}

/** Last resort for an id without a name: at least no underscores. */
export function kpiSinNombre(id: string): string {
  return id.replace(/_/g, ' ');
}

/**
 * The names the KPI bar prints for `ids`: the tree's own `kpi_labels` first,
 * then the shared names, then the id without underscores.
 */
export function nombresKpi(
  ids: string[],
  locale: Locale,
  propios: Record<string, string> = {},
): Record<string, string> {
  return Object.fromEntries(ids.map((id) => [id, propios[id] ?? nombreKpi(id, locale) ?? kpiSinNombre(id)]));
}
