/**
 * Pure Keynesian spending multiplier model for the Eco 1BACH Unit 8
 * (AD-AS model / fiscal policy) interactive calculator.
 *
 * No Preact, no DOM: only the economics, so the multiplier and the spending
 * rounds can be unit-tested independently of the UI.
 *
 * Conceptual link with `ad-as.ts`: an autonomous spending injection (ΔG, ΔI,
 * ΔC0 or ΔX) shifts the aggregate-demand curve. The multiplier explains *how
 * far* AD shifts: the initial injection sets off successive rounds of induced
 * consumption that, summed, amount to ΔY = k · ΔSpending. That ΔY is exactly
 * the kind of horizontal AD shift the AD-AS simulator visualises.
 *
 * Three multiplier formulas, in increasing realism:
 *
 *   Simple (closed economy, no taxes):
 *     k = 1 / (1 − PMC) = 1 / PMS
 *   with PMC the marginal propensity to consume and PMS = 1 − PMC the marginal
 *   propensity to save.
 *
 *   With a proportional income tax t:
 *     k = 1 / (1 − PMC·(1 − t))
 *   Taxes drain part of each income round before it can be consumed, so the
 *   multiplier shrinks.
 *
 *   Open economy, with a marginal propensity to import m:
 *     k = 1 / (1 − PMC·(1 − t) + m)
 *   Imports leak demand abroad, shrinking the multiplier further.
 */

/** Parameters describing the behaviour of the economy. */
export interface MultiplierParams {
  /** Marginal propensity to consume, PMC ∈ [0, 1). */
  pmc: number;
  /** Proportional income tax rate, t ∈ [0, 1). Optional, defaults to 0. */
  t?: number;
  /** Marginal propensity to import, m ∈ [0, 1). Optional, defaults to 0. */
  m?: number;
}

/** Treat |x| below this as zero (avoids floating-point noise). */
const EPS = 1e-12;

/**
 * Marginal propensity to save, PMS = 1 − PMC.
 * (Closed economy without taxes: every euro not consumed is saved.)
 */
export function pms(pmc: number): number {
  return 1 - pmc;
}

/**
 * The "leakage fraction" of each spending round: the share of induced income
 * that does NOT come back as domestic consumption next round.
 *
 *   leak = 1 − PMC·(1 − t) + m
 *
 * The multiplier is simply 1 / leak. With t = 0 and m = 0 this reduces to the
 * simple multiplier 1 / (1 − PMC).
 */
export function leakage(params: MultiplierParams): number {
  const { pmc, t = 0, m = 0 } = params;
  return 1 - pmc * (1 - t) + m;
}

/**
 * Spending multiplier k for the given parameters.
 *
 *   k = 1 / (1 − PMC·(1 − t) + m)
 *
 * Returns Infinity if the leakage is zero (PMC = 1, no taxes, no imports): the
 * geometric series no longer converges. Callers/UI must guard against this.
 */
export function multiplier(params: MultiplierParams): number {
  const leak = leakage(params);
  if (Math.abs(leak) <= EPS) return Infinity;
  return 1 / leak;
}

/** Convenience: simple closed-economy multiplier from PMC alone. */
export function simpleMultiplier(pmc: number): number {
  return multiplier({ pmc });
}

/**
 * Change in equilibrium income produced by an autonomous spending injection.
 *
 *   ΔY = k · ΔSpending
 */
export function deltaIncome(deltaSpending: number, params: MultiplierParams): number {
  return multiplier(params) * deltaSpending;
}

/** One round of the spending cascade. */
export interface SpendingRound {
  /** 1-based round number (round 1 = the initial autonomous injection). */
  round: number;
  /** New spending injected this round (induced consumption from round n−1). */
  spending: number;
  /** Cumulative income generated up to and including this round. */
  cumulative: number;
}

/**
 * First `rounds` terms of the multiplier cascade triggered by an autonomous
 * `deltaSpending` injection.
 *
 * Round 1 is the initial injection itself. Each subsequent round is the induced
 * consumption generated by the previous round's income:
 *
 *   spending(n) = spending(n−1) · PMC·(1 − t) − (imports leak)
 *               = spending(n−1) · (1 − leakage)
 *
 * The "spend ratio" 1 − leakage = PMC·(1 − t) − m is the fraction of each
 * round's income that is re-spent domestically next round. The cumulative sum
 * converges to ΔY = k · deltaSpending as rounds → ∞.
 *
 * @param rounds number of rounds to return (clamped to ≥ 0).
 */
export function spendingRounds(
  deltaSpending: number,
  params: MultiplierParams,
  rounds: number
): SpendingRound[] {
  const n = Math.max(0, Math.floor(rounds));
  // Fraction re-spent domestically each round (the geometric ratio).
  const spendRatio = 1 - leakage(params);
  const out: SpendingRound[] = [];
  let spending = deltaSpending;
  let cumulative = 0;
  for (let r = 1; r <= n; r++) {
    cumulative += spending;
    out.push({ round: r, spending, cumulative });
    spending = spending * spendRatio;
  }
  return out;
}

/** Everything the UI needs for a given configuration. */
export interface MultiplierResult {
  /** The multiplier k. */
  k: number;
  /** Marginal propensity to save (closed economy, no taxes). */
  pms: number;
  /** The autonomous injection that triggered the process. */
  deltaSpending: number;
  /** Total change in equilibrium income, ΔY = k · ΔSpending. */
  deltaIncome: number;
  /** True when k is finite (the series converges). */
  converges: boolean;
}

/** Full solve combining the multiplier with an injection. */
export function solveMultiplier(
  deltaSpending: number,
  params: MultiplierParams
): MultiplierResult {
  const k = multiplier(params);
  const converges = Number.isFinite(k);
  return {
    k,
    pms: pms(params.pmc),
    deltaSpending,
    deltaIncome: converges ? k * deltaSpending : Infinity,
    converges,
  };
}
